// @vitest-environment node
// scripts/check-i18n.mjs, rule 2 (05 §16.5, S27): every ErrorCode (types.gen.ts) and api Code… constant
// (api.gen.ts) has an errors.<code> entry, and limit_reached one per LimitKind. The runtime side of the same mapping
// is lib/errorText.ts (errorText.test.ts).
import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { checkErrorCodes, checkI18n, errorEntryProblem, unionConstants } from '../../scripts/check-i18n.mjs';

const SCRIPT = fileURLToPath(new URL('../../scripts/check-i18n.mjs', import.meta.url));
const WEB_SRC = fileURLToPath(new URL('..', import.meta.url));
const EN_JSON = path.join(WEB_SRC, 'i18n', 'en.json');
const run = promisify(execFile);

const TYPES_GEN = `// Code generated by tygo. DO NOT EDIT.
export const ErrorCodeBadRequest = "bad_request"; // payload invalid
export const ErrorCodeRoomFull = "room_full";
export const ErrorCodeRateLimited = "rate_limited";
export type ErrorCode = typeof ErrorCodeBadRequest | typeof ErrorCodeRoomFull | typeof ErrorCodeRateLimited;
export const AuthSchemeBearer: AuthScheme = "bearer";
`;

const API_GEN = `// Code generated by tygo. DO NOT EDIT.
export const CodeBadRequest = "bad_request";
export const CodeLimitReached = "limit_reached"; // 409: params.limit is a LimitKind

export const CodeInviteExpired = "invite_expired";
export type Code = typeof CodeBadRequest | typeof CodeLimitReached | typeof CodeInviteExpired;
export const LimitKindRooms = "rooms";
export const LimitKindInvites = "invites";
export type LimitKind = typeof LimitKindRooms | typeof LimitKindInvites;
`;

type Catalog = Parameters<typeof errorEntryProblem>[0];
const asCatalog = (c: unknown): Catalog => c as Catalog;

function catalog(): { errors: Record<string, unknown> } {
  return {
    errors: {
      bad_request: 'Bad request.',
      room_full: 'Full.',
      rate_limited: { wait_one: 'Wait {{count}} second.', wait_other: 'Wait {{count}} seconds.', later: 'Later.' },
      limit_reached: { rooms: 'Too many rooms.', invites: 'Too many invites.' },
      invite_expired_one: 'Expired.',
      invite_expired_other: 'Expired.',
    },
  };
}

describe('unionConstants', () => {
  it('returns the union members as constants, in union order, with their declarations', () => {
    const res = unionConstants('api.gen.ts', API_GEN, 'LimitKind');
    expect(res?.problems).toEqual([]);
    expect(res?.constants).toEqual([
      { name: 'LimitKindRooms', value: 'rooms', file: 'api.gen.ts', line: 7, column: 14 },
      { name: 'LimitKindInvites', value: 'invites', file: 'api.gen.ts', line: 8, column: 14 },
    ]);
  });

  it('reads annotated constants and one-member unions', () => {
    const src = 'export const A: T = "a";\nexport type One = typeof A;\n';
    expect(unionConstants('x.ts', src, 'One')?.constants.map((c) => c.value)).toEqual(['a']);
  });

  it('is undefined for a missing type and reports members it cannot resolve', () => {
    expect(unionConstants('x.ts', API_GEN, 'Nope')).toBeUndefined();
    const res = unionConstants('x.ts', 'export const A = "a";\nexport type U = typeof A | typeof B | "c";\n', 'U');
    expect(res?.constants.map((c) => c.value)).toEqual(['a']);
    expect(res?.problems).toHaveLength(2);
  });
});

describe('errorEntryProblem', () => {
  it.each([
    ['bad_request', undefined, null], // a string
    ['rate_limited', undefined, null], // an object with messages
    ['invite_expired', undefined, null], // plural forms
    ['limit_reached', ['rooms', 'invites'], null],
    ['limit_reached', ['rooms', 'invites', 'pending_signups'], 'needs errors.limit_reached.pending_signups'],
    ['bad_request', ['rooms'], 'needs errors.bad_request.rooms'],
    ['missing_code', undefined, 'has no errors.missing_code'],
  ])('%s (sub-keys %j) → %s', (code, subKeys, want) => {
    expect(errorEntryProblem(asCatalog(catalog()), code, subKeys)).toBe(want);
  });

  it('an object without any message does not count', () => {
    const c = catalog();
    c.errors = { ...c.errors, room_full: { nested: {} } };
    expect(errorEntryProblem(asCatalog(c), 'room_full')).toBe('has no errors.room_full');
  });
});

describe('check-i18n.mjs error-code rule on fixture trees', () => {
  let dir = '';
  let srcDir = '';
  let catalogPath = '';

  const writeCatalog = (c: unknown) => writeFile(catalogPath, JSON.stringify(c));

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), 'isshoni-check-i18n-errors-'));
    srcDir = path.join(dir, 'src');
    catalogPath = path.join(srcDir, 'i18n', 'en.json');
    await mkdir(path.join(srcDir, 'i18n'), { recursive: true });
    await mkdir(path.join(srcDir, 'protocol'), { recursive: true });
    await writeFile(path.join(srcDir, 'protocol', 'types.gen.ts'), TYPES_GEN);
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), API_GEN);
    await writeCatalog(catalog());
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('passes when every code has its entry; a code shared by both files is counted once', async () => {
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems).toEqual([]);
    expect(res.errorCodes).toBe(5);
    const { stdout } = await run(process.execPath, [SCRIPT, '--src', srcDir, '--catalog', catalogPath]);
    expect(stdout).toMatch(/check:i18n: ok \(0 message keys in 0 files\), 5 error codes/);
  });

  it('fails when an ErrorCode has no errors.<code>, pointing at the constant', async () => {
    const c = catalog();
    delete c.errors['room_full'];
    await writeCatalog(c);
    const failed = run(process.execPath, [SCRIPT, '--src', srcDir, '--catalog', catalogPath]);
    await expect(failed).rejects.toMatchObject({ code: 1 });
    const err = (await failed.catch((e: unknown) => e)) as { stderr: string };
    expect(err.stderr).toMatch(
      /types\.gen\.ts:3:14: error code "room_full" \(ErrorCodeRoomFull\) has no errors\.room_full in /,
    );
    expect(err.stderr).toMatch(/check:i18n: 1 problem\(s\)/);
  });

  it('fails when an api Code has no errors.<code>', async () => {
    const c = catalog();
    delete c.errors['invite_expired_one'];
    delete c.errors['invite_expired_other'];
    await writeCatalog(c);
    const { problems } = await checkErrorCodes({ srcDir, catalog: asCatalog(c), catalogName: 'en.json' });
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatchObject({ line: 5, column: 14 });
    expect(problems[0]?.message).toMatch(/"invite_expired" \(CodeInviteExpired\) has no errors\.invite_expired/);
  });

  it('fails when limit_reached lacks a LimitKind sub-key', async () => {
    const c = catalog();
    c.errors = { ...c.errors, limit_reached: { rooms: 'Too many rooms.' } };
    const { problems } = await checkErrorCodes({ srcDir, catalog: asCatalog(c), catalogName: 'en.json' });
    expect(problems.map((p) => p.message)).toEqual([
      'error code "limit_reached" (CodeLimitReached) needs errors.limit_reached.invites in en.json',
    ]);
  });

  it('fails when a shared code (in both files) is missing, once', async () => {
    const c = catalog();
    delete c.errors['bad_request'];
    const { problems } = await checkErrorCodes({ srcDir, catalog: asCatalog(c), catalogName: 'en.json' });
    expect(problems).toHaveLength(1);
    expect(problems[0]?.message).toMatch(/"bad_request" \(ErrorCodeBadRequest\)/);
  });

  it('fails when one generated file is missing or has no union', async () => {
    await rm(path.join(srcDir, 'protocol', 'api.gen.ts'));
    let res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems.map((p) => p.message)).toEqual(['generated file missing: run `task gen`']);
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), 'export const X = "x";\n');
    res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems.map((p) => p.message)).toEqual([
      'no `export type Code` union found',
      'no `export type LimitKind` union found',
    ]);
  });

  it('skips the rule, with a note, for a src tree without generated files', async () => {
    await rm(path.join(srcDir, 'protocol'), { recursive: true });
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res).toMatchObject({ problems: [], errorCodes: null });
    const { stdout } = await run(process.execPath, [SCRIPT, '--src', srcDir, '--catalog', catalogPath]);
    expect(stdout).toMatch(/error-code rule skipped/);
  });
});

describe('check-i18n.mjs on this package', () => {
  it('passes: en.json has every generated error code', async () => {
    const res = await checkI18n({ srcDir: WEB_SRC, catalogPath: EN_JSON });
    expect(res.problems).toEqual([]);
    expect(res.errorCodes).toBeGreaterThanOrEqual(75);
  });

  it('fails when an errors.<code> key is removed from a copy of en.json', async () => {
    const dir = await mkdtemp(path.join(tmpdir(), 'isshoni-check-i18n-en-'));
    try {
      const en = JSON.parse(await readFile(EN_JSON, 'utf8')) as { errors: Record<string, unknown> };
      delete en.errors['session_revoked'];
      delete (en.errors['limit_reached'] as Record<string, unknown>)['pending_signups'];
      const copy = path.join(dir, 'en.json');
      await writeFile(copy, JSON.stringify(en));
      const failed = run(process.execPath, [SCRIPT, '--src', WEB_SRC, '--catalog', copy]);
      await expect(failed).rejects.toMatchObject({ code: 1 });
      const err = (await failed.catch((e: unknown) => e)) as { stderr: string };
      expect(err.stderr).toMatch(
        /error code "session_revoked" \(ErrorCodeSessionRevoked\) has no errors\.session_revoked/,
      );
      expect(err.stderr).toMatch(
        /error code "limit_reached" \(CodeLimitReached\) needs errors\.limit_reached\.pending_signups/,
      );
      expect(err.stderr).toMatch(/check:i18n: 2 problem\(s\)/);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
