// @vitest-environment node
// scripts/check-i18n.mjs, rule 3 (05 §16.5, S37): every CloudProvider constant of api.gen.ts has a
// fix.firewall.<provider> message and every NATKind constant a conntest.nat.<nat> message. These keys are built from
// the server's ids (fixText.ts), so rule 1 never sees them as t('…') literals.
import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { checkConstantKeys, checkI18n, CONSTANT_KEYED } from '../../scripts/check-i18n.mjs';

const SCRIPT = fileURLToPath(new URL('../../scripts/check-i18n.mjs', import.meta.url));
const WEB_SRC = fileURLToPath(new URL('..', import.meta.url));
const EN_JSON = path.join(WEB_SRC, 'i18n', 'en.json');
const run = promisify(execFile);

const TYPES_GEN = `// Code generated by tygo. DO NOT EDIT.
export const ErrorCodeBadRequest = "bad_request";
export type ErrorCode = typeof ErrorCodeBadRequest;
`;

const API_GEN = `// Code generated by tygo. DO NOT EDIT.
/**
 * CloudProvider is a hosting provider detected from DMI data (04 §13.3).
 */
export const CloudProviderAWS = "aws";
export const CloudProviderHetzner = "hetzner";
export const CloudProviderUnknown = "unknown";
export type CloudProvider = typeof CloudProviderAWS | typeof CloudProviderHetzner | typeof CloudProviderUnknown;
export const NATKindNone = "none"; // the public IP is on an interface
export const NATKindPortForward = "port_forward";
export type NATKind = typeof NATKindNone | typeof NATKindPortForward;
export const CodeBadRequest = "bad_request";
export type Code = typeof CodeBadRequest;
export const LimitKindRooms = "rooms";
export type LimitKind = typeof LimitKindRooms;
`;

type Catalog = Parameters<typeof checkConstantKeys>[0]['catalog'];
const asCatalog = (c: unknown): Catalog => c as Catalog;

interface FixtureCatalog {
  errors: Record<string, unknown>;
  fix: { firewall: Record<string, unknown> };
  conntest: { nat: Record<string, unknown> };
}

function catalog(): FixtureCatalog {
  return {
    errors: { bad_request: 'Bad request.', limit_reached: { rooms: 'Too many rooms.' } },
    fix: { firewall: { aws: 'Security group.', hetzner: 'Cloud Firewall.', unknown: "Your provider's firewall." } },
    conntest: { nat: { none: 'No NAT.', port_forward: 'Forward the ports.' } },
  };
}

describe('check-i18n.mjs provider and NAT rule on fixture trees', () => {
  let dir = '';
  let srcDir = '';
  let catalogPath = '';

  const writeCatalog = (c: unknown) => writeFile(catalogPath, JSON.stringify(c));
  const cli = () => run(process.execPath, [SCRIPT, '--src', srcDir, '--catalog', catalogPath]);
  const check = (c: unknown) => checkConstantKeys({ srcDir, catalog: asCatalog(c), catalogName: 'en.json' });

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), 'isshoni-check-i18n-fix-'));
    srcDir = path.join(dir, 'src');
    catalogPath = path.join(srcDir, 'i18n', 'en.json');
    await mkdir(path.join(srcDir, 'i18n'), { recursive: true });
    await mkdir(path.join(srcDir, 'protocol'), { recursive: true });
    await writeFile(path.join(srcDir, 'protocol', 'types.gen.ts'), TYPES_GEN);
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), API_GEN);
    await writeCatalog(catalog());
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('passes when every provider and NAT kind has its text, and says how many it checked', async () => {
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems).toEqual([]);
    expect(res.constantKeys).toEqual({ CloudProvider: 3, NATKind: 2 });
    const { stdout } = await cli();
    expect(stdout).toMatch(
      /check:i18n: ok \(0 message keys in 0 files\), 1 error codes, 3 cloud providers, 2 NAT kinds/,
    );
  });

  it('fails when a CloudProvider constant has no fix.firewall.<provider>, pointing at the constant', async () => {
    const c = catalog();
    delete c.fix.firewall['hetzner'];
    await writeCatalog(c);
    const failed = cli();
    await expect(failed).rejects.toMatchObject({ code: 1 });
    const err = (await failed.catch((e: unknown) => e)) as { stderr: string };
    expect(err.stderr).toMatch(
      /api\.gen\.ts:6:14: cloud provider "hetzner" \(CloudProviderHetzner\) has no fix\.firewall\.hetzner in /,
    );
    expect(err.stderr).toMatch(/check:i18n: 1 problem\(s\)/);
  });

  it('fails when a NATKind constant has no conntest.nat.<nat>', async () => {
    const c = catalog();
    delete c.conntest.nat['port_forward'];
    await writeCatalog(c);
    const failed = cli();
    await expect(failed).rejects.toMatchObject({ code: 1 });
    const err = (await failed.catch((e: unknown) => e)) as { stderr: string };
    expect(err.stderr).toMatch(
      /api\.gen\.ts:10:14: NAT kind "port_forward" \(NATKindPortForward\) has no conntest\.nat\.port_forward in /,
    );
    expect(err.stderr).toMatch(/check:i18n: 1 problem\(s\)/);
  });

  it('reports every missing text, also when the whole family is gone', async () => {
    const { problems, counts } = await check({ errors: catalog().errors });
    expect(counts).toEqual({ CloudProvider: 3, NATKind: 2 });
    expect(problems.map((p) => p.message)).toEqual([
      'cloud provider "aws" (CloudProviderAWS) has no fix.firewall.aws in en.json',
      'cloud provider "hetzner" (CloudProviderHetzner) has no fix.firewall.hetzner in en.json',
      'cloud provider "unknown" (CloudProviderUnknown) has no fix.firewall.unknown in en.json',
      'NAT kind "none" (NATKindNone) has no conntest.nat.none in en.json',
      'NAT kind "port_forward" (NATKindPortForward) has no conntest.nat.port_forward in en.json',
    ]);
    expect(problems[0]).toMatchObject({ line: 5, column: 14 });
  });

  it('needs a message: an object with sub-keys or a text in the other family does not count', async () => {
    const c = catalog();
    c.fix.firewall['aws'] = { title: 'AWS', body: 'Security group.' };
    delete c.conntest.nat['none'];
    c.fix.firewall['none'] = 'a NAT kind is not a provider';
    const { problems } = await check(c);
    expect(problems.map((p) => p.message)).toEqual([
      'cloud provider "aws" (CloudProviderAWS): fix.firewall.aws has sub-keys, not a message in en.json',
      'NAT kind "none" (NATKindNone) has no conntest.nat.none in en.json',
    ]);
  });

  it('accepts plural forms as a message', async () => {
    const c = catalog();
    delete c.fix.firewall['aws'];
    c.fix.firewall['aws_one'] = 'One rule.';
    c.fix.firewall['aws_other'] = '{{count}} rules.';
    expect((await check(c)).problems).toEqual([]);
  });

  it('a constant added in Go and regenerated fails until en.json has its text', async () => {
    const more = API_GEN.replace(
      'export type NATKind = typeof NATKindNone | typeof NATKindPortForward;',
      'export const NATKindDouble = "double";\n' +
        'export type NATKind = typeof NATKindNone | typeof NATKindPortForward | typeof NATKindDouble;',
    );
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), more);
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems.map((p) => p.message)).toEqual([
      expect.stringMatching(/^NAT kind "double" \(NATKindDouble\) has no conntest\.nat\.double in /),
    ]);
    expect(res.constantKeys).toEqual({ CloudProvider: 3, NATKind: 3 });
  });

  it('fails when api.gen.ts declares only one of the two unions', async () => {
    const onlyProviders = API_GEN.replace(/^export (const NATKind|type NATKind).*\n/gm, '');
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), onlyProviders);
    const { problems, counts } = await check(catalog());
    expect(problems.map((p) => p.message)).toEqual(['no `export type NATKind` union found']);
    expect(counts).toEqual({ CloudProvider: 3 });
    await expect(cli()).rejects.toMatchObject({ code: 1 });
  });

  it('skips the rule, with a note, when the tree has neither the unions nor the texts', async () => {
    const neither = API_GEN.replace(/^export (const|type) (CloudProvider|NATKind).*\n/gm, '');
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), neither);
    await writeCatalog({ errors: catalog().errors });
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res).toMatchObject({ problems: [], errorCodes: 1, constantKeys: null });
    const { stdout } = await cli();
    expect(stdout).toMatch(/note: no CloudProvider or NATKind in protocol\/api\.gen\.ts.*fix-text rule skipped/);
    expect(stdout).toMatch(/check:i18n: ok \(0 message keys in 0 files\), 1 error codes\n/);
  });

  it('does not skip when the catalog has the texts: unions that vanished from api.gen.ts are a problem', async () => {
    const neither = API_GEN.replace(/^export (const|type) (CloudProvider|NATKind).*\n/gm, '');
    await writeFile(path.join(srcDir, 'protocol', 'api.gen.ts'), neither);
    const { problems, counts } = await check(catalog());
    expect(problems.map((p) => p.message)).toEqual([
      'no `export type CloudProvider` union found',
      'no `export type NATKind` union found',
    ]);
    expect(counts).toEqual({});
    await expect(cli()).rejects.toMatchObject({ code: 1 });
    // One family of texts is enough to ask for both unions.
    const onlyNat = await check({ errors: catalog().errors, conntest: catalog().conntest });
    expect(onlyNat.problems).toHaveLength(2);
  });

  it('skips the rule without a second problem when api.gen.ts is missing (rule 2 reports the file)', async () => {
    await rm(path.join(srcDir, 'protocol', 'api.gen.ts'));
    const res = await checkI18n({ srcDir, catalogPath });
    expect(res.problems.map((p) => p.message)).toEqual(['generated file missing: run `task gen`']);
    expect(res.constantKeys).toBeNull();
  });
});

describe('check-i18n.mjs on this package', () => {
  it('declares the two families of 05 §16.5', () => {
    expect(CONSTANT_KEYED.map((f) => [f.typeName, f.prefix])).toEqual([
      ['CloudProvider', 'fix.firewall'],
      ['NATKind', 'conntest.nat'],
    ]);
  });

  it('passes: en.json has every fix.firewall.<provider> and conntest.nat.<nat> text', async () => {
    const res = await checkI18n({ srcDir: WEB_SRC, catalogPath: EN_JSON });
    expect(res.problems).toEqual([]);
    // 04 §13.3 has 13 provider ids and 04 §7.4 six NAT kinds; a rule that found none would be skipping.
    expect(res.constantKeys).toEqual({ CloudProvider: 13, NATKind: 6 });
    const { stdout } = await run(process.execPath, [SCRIPT]);
    expect(stdout).toMatch(/, 13 cloud providers, 6 NAT kinds\n$/);
    expect(stdout).not.toMatch(/skipped/);
  });

  it('fails when a provider or NAT text is removed from a copy of en.json', async () => {
    const dir = await mkdtemp(path.join(tmpdir(), 'isshoni-check-i18n-fix-en-'));
    try {
      const en = JSON.parse(await readFile(EN_JSON, 'utf8')) as FixtureCatalog;
      delete en.fix.firewall['oracle'];
      delete en.conntest.nat['cgnat_likely'];
      const copy = path.join(dir, 'en.json');
      await writeFile(copy, JSON.stringify(en));
      const failed = run(process.execPath, [SCRIPT, '--src', WEB_SRC, '--catalog', copy]);
      await expect(failed).rejects.toMatchObject({ code: 1 });
      const err = (await failed.catch((e: unknown) => e)) as { stderr: string };
      expect(err.stderr).toMatch(/cloud provider "oracle" \(CloudProviderOracle\) has no fix\.firewall\.oracle in /);
      expect(err.stderr).toMatch(
        /NAT kind "cgnat_likely" \(NATKindCGNATLikely\) has no conntest\.nat\.cgnat_likely in /,
      );
      expect(err.stderr).toMatch(/check:i18n: 2 problem\(s\)/);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
