// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/protocol/api. DO NOT EDIT.

//////////
// source: conntest.go

/**
 * Transport is one way media reaches the server: the ICE transports of 04 §7.3. It is the conntest request's
 * transport, AdvertisedAddr.Via, ConnectionLive.Transport and a key of TransportCounts.
 */
export const TransportUDP = "udp"; // UDP mux on listen.ice_udp (7882)
export const TransportTCP443 = "tcp443"; // ICE-TCP through the 443 first-byte multiplexer
export const TransportTCP7882 = "tcp7882"; // ICE-TCP on listen.ice_tcp (7882)
export type Transport = typeof TransportUDP | typeof TransportTCP443 | typeof TransportTCP7882;
/**
 * CloudProvider is a hosting provider detected from DMI data (04 §13.3). 05 has a fix.firewall.<provider> text for
 * each value, and 06's site an install/vps#<provider> anchor.
 */
export const CloudProviderAWS = "aws";
export const CloudProviderGCP = "gcp";
export const CloudProviderAzure = "azure";
export const CloudProviderOracle = "oracle";
export const CloudProviderHetzner = "hetzner";
export const CloudProviderDigitalOcean = "digitalocean";
export const CloudProviderVultr = "vultr";
export const CloudProviderLinode = "linode";
export const CloudProviderScaleway = "scaleway";
export const CloudProviderOVH = "ovh";
export const CloudProviderAlibaba = "alibaba";
export const CloudProviderTencent = "tencent";
export const CloudProviderUnknown = "unknown";
export type CloudProvider = typeof CloudProviderAWS | typeof CloudProviderGCP | typeof CloudProviderAzure | typeof CloudProviderOracle | typeof CloudProviderHetzner | typeof CloudProviderDigitalOcean | typeof CloudProviderVultr | typeof CloudProviderLinode | typeof CloudProviderScaleway | typeof CloudProviderOVH | typeof CloudProviderAlibaba | typeof CloudProviderTencent | typeof CloudProviderUnknown;
/**
 * NATKind classifies the server's public IPv4 path (04 §7.4). 05 has a conntest.nat.<nat> text for each value.
 */
export const NATKindNone = "none"; // the public IP is on an interface
export const NATKindOneToOne = "one_to_one"; // 1:1 NAT (cloud provider or container)
export const NATKindPortForward = "port_forward"; // a home router forwarding ports
export const NATKindSymmetric = "symmetric"; // mapped ports differ per destination; friends probably can't connect
export const NATKindCGNATLikely = "cgnat_likely"; // a 100.64.0.0/10 address on a non-Tailscale interface
export const NATKindUnknown = "unknown";
export type NATKind = typeof NATKindNone | typeof NATKindOneToOne | typeof NATKindPortForward | typeof NATKindSymmetric | typeof NATKindCGNATLikely | typeof NATKindUnknown;
/**
 * ContainerKind is the container runtime the server runs in (ConnTestServerInfo.Container, DoctorEnv.Container).
 */
export const ContainerKindNone = "none";
export const ContainerKindDocker = "docker";
export const ContainerKindPodman = "podman";
export const ContainerKindOther = "other";
export type ContainerKind = typeof ContainerKindNone | typeof ContainerKindDocker | typeof ContainerKindPodman | typeof ContainerKindOther;
/**
 * ConnTestRequest is POST /api/v1/conntest (04 §7.7): a real ICE check on one transport.
 */
export interface ConnTestRequest {
  transport: Transport;
  offer: string; // SDP with one data channel; fmt and slog show only its length (secret.go)
}
/**
 * ConnTestResponse is the reply to POST /api/v1/conntest. Errors: 400 bad_sdp, 409 transport_disabled
 * (params.transport), 429 rate_limited, 503 not_ready.
 */
export interface ConnTestResponse {
  answer: string; // complete, non-trickle SDP with only that transport's candidates
  expiresInS: number /* int */; // the probe PC closes after this many seconds (20)
  server: ConnTestServerInfo;
}
/**
 * ConnTestServerInfo lets the SPA show provider-specific fix text (to admins only).
 */
export interface ConnTestServerInfo {
  publicIp: string; // "" when no public IPv4 is known
  provider: CloudProvider;
  container: ContainerKind;
  udpPort: number /* int */; // 0 when UDP is off
  tcpPorts: number /* int */[]; // e.g. [443, 7882]
  nat: NATKind;
}

//////////
// source: doctor.go

/**
 * DoctorReportSchema is DoctorReport.Schema. It increases only on breaking changes; within a schema fields are only
 * added.
 */
export const DoctorReportSchema = 1;
/**
 * DoctorStatus is the result of one check (04 §13.2).
 */
export const DoctorStatusOK = "ok";
export const DoctorStatusWarn = "warn";
export const DoctorStatusFail = "fail";
export const DoctorStatusSkip = "skip";
export const DoctorStatusInfo = "info";
export type DoctorStatus = typeof DoctorStatusOK | typeof DoctorStatusWarn | typeof DoctorStatusFail | typeof DoctorStatusSkip | typeof DoctorStatusInfo;
/**
 * DoctorMode says where the checks ran (04 §13.1).
 */
export const DoctorModeServer = "server"; // inside the server (dashboard, POST /api/v1/admin/doctor)
export const DoctorModeCLIWithServer = "cli-with-server"; // the CLI asked the running server over the admin socket
export const DoctorModeCLIOffline = "cli-offline"; // no server: the CLI ran the checks itself
export type DoctorMode = typeof DoctorModeServer | typeof DoctorModeCLIWithServer | typeof DoctorModeCLIOffline;
/**
 * DoctorReport is one doctor run (04 §13.5). Message and Fix in each check are English for the CLI; 05 renders
 * Code, Params and FixCode from its catalog.
 */
export interface DoctorReport {
  schema: number /* int */; // DoctorReportSchema
  version: string;
  ranAt: string;
  mode: DoctorMode;
  summary: DoctorCounts;
  env: DoctorEnv;
  checks: DoctorCheck[];
  bandwidth?: BandwidthEstimate;
}
/**
 * DoctorCounts is DoctorReport.Summary: the number of checks per status.
 */
export interface DoctorCounts {
  ok: number /* int */;
  warn: number /* int */;
  fail: number /* int */;
  skip: number /* int */;
  info: number /* int */;
}
/**
 * DoctorEnv describes the host doctor ran on.
 */
export interface DoctorEnv {
  os: string;
  arch: string;
  kernel: string;
  container: ContainerKind;
  systemd: boolean;
  provider: CloudProvider;
  user: string;
}
/**
 * DoctorCheck is one check's result. ID is one of the check ids of 04 §13.2 (doctor.CheckIDs).
 */
export interface DoctorCheck {
  id: string;
  status: DoctorStatus;
  code: string; // message template key, e.g. "udp_buffers.low"
  params?: { [key: string]: any};
  message: string; // English, for the CLI
  fixCode?: string;
  fix?: string; // English, for the CLI
  localOnly: boolean;
  durationMs: number /* int64 */;
}
/**
 * BandwidthQuality is the full-layer quality the calculator assumes (04 §13.4).
 */
export const BandwidthQuality1080p60 = "1080p60"; // 8 Mbps
export const BandwidthQuality1440p60 = "1440p60"; // 16 Mbps
export const BandwidthQuality2160p60 = "2160p60"; // 32 Mbps
export type BandwidthQuality = typeof BandwidthQuality1080p60 | typeof BandwidthQuality1440p60 | typeof BandwidthQuality2160p60;
/**
 * BandwidthPreset is the sharing preset the calculator assumes: it sets the audio bitrate.
 */
export const BandwidthPresetAuto = "auto"; // 128 kbps audio
export const BandwidthPresetMovie = "movie"; // 256 kbps audio
export type BandwidthPreset = typeof BandwidthPresetAuto | typeof BandwidthPresetMovie;
/**
 * BandwidthInput is the calculator's input: doctor's flags and the query of GET /api/v1/admin/bandwidth.
 */
export interface BandwidthInput {
  people: number /* int */;
  sharing: number /* int */;
  thumbnails: number /* int */;
  quality: BandwidthQuality;
  preset: BandwidthPreset;
  hours: number /* float64 */;
}
/**
 * BandwidthEstimate is the calculator's output (04 §13.4): GET /api/v1/admin/bandwidth and DoctorReport.Bandwidth.
 */
export interface BandwidthEstimate {
  input: BandwidthInput;
  perViewerMbps: BandwidthPerViewer;
  egressMediaMbps: number /* float64 */;
  egressWireMbps: number /* float64 */;
  ingressMediaMbps: number /* float64 */;
  transferPerSessionGb: number /* float64 */; // 1 GB = 10⁹ bytes, on the wire
}
/**
 * BandwidthPerViewer is the egress to one person, depending on whether that person shares too.
 */
export interface BandwidthPerViewer {
  sharer: number /* float64 */;
  viewer: number /* float64 */;
}

//////////
// source: encode.go


//////////
// source: errors.go

/**
 * Error is both the REST error body and the Go error value that store, auth, httpapi and 04's handlers return
 * (03 §12.2). httpapi.WriteError sends it as ErrorResponse with the status StatusOf(Code), and a Retry-After header
 * when RetryAfter is set. It never carries English text.
 */
export interface Error {
  code: string;
  fields?: { [key: string]: string}; // validation_failed: field JSON name → Field* code
  params?: { [key: string]: any}; // e.g. {"limit": "rooms"} (Param* keys); never prose
  retryAfter?: number /* int */; // seconds; also sent as the Retry-After header
  requestId?: string; // 04's request ID, set on 500 internal (bug reports)
}
/**
 * ErrorResponse is the only REST error shape: {"error": {code, fields?, params?, retryAfter?, requestId?}}. 03's
 * /api/v1 routes, 04's routes and 04's global middleware all use it; the admin socket wraps it (04 §12.1).
 */
export interface ErrorResponse {
  error: Error;
}
export const CodeBadRequest = "bad_request"; // 400: malformed JSON (incl. trailing data), or a bad path or query parameter
export const CodeValidationFailed = "validation_failed"; // 422: see Error.Fields
export const CodeUnsupportedMediaType = "unsupported_media_type"; // 415: unsafe request without Content-Type: application/json
export const CodePayloadTooLarge = "payload_too_large"; // 413: body over the limit
export const CodeMethodNotAllowed = "method_not_allowed"; // 405: known /api/v1 path, wrong method (Allow header lists the methods)
export const CodeUnauthenticated = "unauthenticated"; // 401: no valid session (or bearer)

export const CodeInvalidCredentials = "invalid_credentials"; // 401: wrong username or password (the same answer for unknown users)
export const CodeWrongPassword = "wrong_password"; // 403: re-authentication failed (currentPassword)
export const CodeForbidden = "forbidden"; // 403: not allowed for this role
export const CodeCSRFFailed = "csrf_failed"; // 403: cross-origin unsafe request
export const CodeAccountPending = "account_pending"; // 403: correct password, but the sign-up awaits approval
export const CodeAccountDisabled = "account_disabled"; // 403: correct password, but the account is disabled
export const CodeRegistrationClosed = "registration_closed"; // 403: registration mode closed
export const CodeInviteRequired = "invite_required"; // 403: registration mode invite and no invite token
export const CodeNotFound = "not_found"; // 404: generic; also an unknown /api/ route (03 inside /api/v1, 04 elsewhere)
export const CodeUserNotFound = "user_not_found"; // 404
export const CodeRoomNotFound = "room_not_found"; // 404
export const CodeInviteInvalid = "invite_invalid"; // 404: unknown invite token
export const CodeInviteExpired = "invite_expired"; // 410
export const CodeInviteUsedUp = "invite_used_up"; // 410
export const CodeInviteRevoked = "invite_revoked"; // 410
export const CodeSetupUnavailable = "setup_unavailable"; // 404: an admin already exists
export const CodeSetupTokenInvalid = "setup_token_invalid"; // 404: unknown, replaced or expired setup token
export const CodeResetTokenInvalid = "reset_token_invalid"; // 404: unknown, used or expired reset token
export const CodeUsernameTaken = "username_taken"; // 409
export const CodeRoomNameTaken = "room_name_taken"; // 409
export const CodeLastAdmin = "last_admin"; // 409: would leave no active admin
export const CodeSelfActionForbidden = "self_action_forbidden"; // 409: use the self-service endpoint instead
export const CodeRoomIsDefault = "room_is_default"; // 409: Lounge can't be deleted
export const CodeLimitReached = "limit_reached"; // 409: params.limit is a LimitKind
export const CodeSettingLocked = "setting_locked"; // 409: params.field names the setting pinned by config
export const CodePushEndpointRejected = "push_endpoint_rejected"; // 422: params.reason is a PushRejectReason
export const CodePushUnavailable = "push_unavailable"; // 503: push is off (push.enabled = false, 04)
export const CodeRateLimited = "rate_limited"; // 429: Error.RetryAfter
export const CodeServerBusy = "server_busy"; // 503: hash queue full or the auth-hash budget is empty; Error.RetryAfter
export const CodeInternal = "internal"; // 500: logged with Error.RequestID (04), never with details on the wire
export const CodeBadSDP = "bad_sdp"; // 400 (04): /conntest offer isn't a data-channel-only SDP
export const CodeTransportDisabled = "transport_disabled"; // 409 (04): /conntest transport has no listener; params.transport
export const CodeDoctorBusy = "doctor_busy"; // 429 (04): a doctor run is in progress or ran < 10 s ago; Error.RetryAfter
export const CodeNotReady = "not_ready"; // 503 (04): the media plane isn't ready yet
export const CodeServerShutdown = "server_shutdown"; // 503 (04): the server is stopping or restarting; Retry-After: 5
export const CodeBackupInvalid = "backup_invalid"; // 400 (04, admin socket only): the archive or DB file failed validation
export const CodeBackupNewer = "backup_newer"; // 409 (04, admin socket only): the backup's schema is newer than this binary
export const CodeRestoreInProgress = "restore_in_progress"; // 409 (04, admin socket only)
export const CodeInsufficientStorage = "insufficient_storage"; // 507 (04, admin socket only): not enough free disk space
export const CodeInvalidToken = "invalid_token"; // 401, later (M2): bearer access token expired or unknown: refresh
export const CodeAuthorizationPending = "authorization_pending"; // 400, later (M2): RFC 8628
export const CodeSlowDown = "slow_down"; // 400, later (M2): RFC 8628
export const CodeAccessDenied = "access_denied"; // 400, later (M2): RFC 8628
export const CodeExpiredToken = "expired_token"; // 400, later (M2): RFC 8628
export const CodeInvalidGrant = "invalid_grant"; // 400, later (M2): OAuth refresh token reuse or unknown grant
export const CodeDeviceCodeInvalid = "device_code_invalid"; // 404, later (M2): unknown or expired user code
/**
 * Error codes (03 §12.2). A code is stable forever: it is never renamed or reused with another meaning. Every code is
 * M1 unless marked; (04) marks the rows of 04's routes and middleware (04 §9.4). Eight codes are shared with 01's
 * WebSocket errors and must mean the same thing there: bad_request, unauthenticated, forbidden, account_disabled,
 * room_not_found, rate_limited, internal and server_shutdown.
 */
export type Code = typeof CodeBadRequest | typeof CodeValidationFailed | typeof CodeUnsupportedMediaType | typeof CodePayloadTooLarge | typeof CodeMethodNotAllowed | typeof CodeUnauthenticated | typeof CodeInvalidCredentials | typeof CodeWrongPassword | typeof CodeForbidden | typeof CodeCSRFFailed | typeof CodeAccountPending | typeof CodeAccountDisabled | typeof CodeRegistrationClosed | typeof CodeInviteRequired | typeof CodeNotFound | typeof CodeUserNotFound | typeof CodeRoomNotFound | typeof CodeInviteInvalid | typeof CodeInviteExpired | typeof CodeInviteUsedUp | typeof CodeInviteRevoked | typeof CodeSetupUnavailable | typeof CodeSetupTokenInvalid | typeof CodeResetTokenInvalid | typeof CodeUsernameTaken | typeof CodeRoomNameTaken | typeof CodeLastAdmin | typeof CodeSelfActionForbidden | typeof CodeRoomIsDefault | typeof CodeLimitReached | typeof CodeSettingLocked | typeof CodePushEndpointRejected | typeof CodePushUnavailable | typeof CodeRateLimited | typeof CodeServerBusy | typeof CodeInternal | typeof CodeBadSDP | typeof CodeTransportDisabled | typeof CodeDoctorBusy | typeof CodeNotReady | typeof CodeServerShutdown | typeof CodeBackupInvalid | typeof CodeBackupNewer | typeof CodeRestoreInProgress | typeof CodeInsufficientStorage | typeof CodeInvalidToken | typeof CodeAuthorizationPending | typeof CodeSlowDown | typeof CodeAccessDenied | typeof CodeExpiredToken | typeof CodeInvalidGrant | typeof CodeDeviceCodeInvalid;
export const FieldRequired = "required";
export const FieldTooShort = "too_short";
export const FieldTooLong = "too_long";
export const FieldInvalid = "invalid";
export const FieldReserved = "reserved";
export const FieldTooCommon = "too_common";
export const FieldSameAsUsername = "same_as_username";
export const FieldOutOfRange = "out_of_range";
export const FieldNotAllowed = "not_allowed";
/**
 * Field codes: the values of Error.Fields for validation_failed (03 §12.2).
 */
export type Field = typeof FieldRequired | typeof FieldTooShort | typeof FieldTooLong | typeof FieldInvalid | typeof FieldReserved | typeof FieldTooCommon | typeof FieldSameAsUsername | typeof FieldOutOfRange | typeof FieldNotAllowed;
export const ParamLimit = "limit"; // limit_reached: a LimitKind
export const ParamField = "field"; // setting_locked: the setting's JSON name (Settings)
export const ParamReason = "reason"; // push_endpoint_rejected: a PushRejectReason
export const ParamTransport = "transport"; // transport_disabled: a Transport
/**
 * Keys of Error.Params.
 */
export type Param = typeof ParamLimit | typeof ParamField | typeof ParamReason | typeof ParamTransport;
/**
 * LimitKind is params.limit of limit_reached (03 §12.2).
 */
export const LimitKindRooms = "rooms"; // 200 rooms per server
export const LimitKindInvites = "invites"; // 100 active invites per server
export const LimitKindMemberInvites = "member_invites"; // 10 active invites per member
export const LimitKindPendingSignups = "pending_signups"; // 50 pending sign-ups
export type LimitKind = typeof LimitKindRooms | typeof LimitKindInvites | typeof LimitKindMemberInvites | typeof LimitKindPendingSignups;
/**
 * PushRejectReason is params.reason of push_endpoint_rejected (03 §12.4.6). too_long and bad_keys come from 03's
 * handler (body shape); the others from 04's Push.ValidateEndpoint.
 */
export const PushRejectReasonTooLong = "too_long";
export const PushRejectReasonBadKeys = "bad_keys";
export const PushRejectReasonNotHTTPS = "not_https";
export const PushRejectReasonBadPort = "bad_port";
export const PushRejectReasonUserinfo = "userinfo";
export const PushRejectReasonIPLiteral = "ip_literal";
export const PushRejectReasonPrivateAddress = "private_address";
export const PushRejectReasonUnresolvable = "unresolvable";
export type PushRejectReason = typeof PushRejectReasonTooLong | typeof PushRejectReasonBadKeys | typeof PushRejectReasonNotHTTPS | typeof PushRejectReasonBadPort | typeof PushRejectReasonUserinfo | typeof PushRejectReasonIPLiteral | typeof PushRejectReasonPrivateAddress | typeof PushRejectReasonUnresolvable;

//////////
// source: ops.go

/**
 * TLSMode is the effective tls.mode (04 §8.1).
 */
export const TLSModeAuto = "auto";
export const TLSModeIP = "ip";
export const TLSModeManual = "manual";
export const TLSModeOff = "off";
export type TLSMode = typeof TLSModeAuto | typeof TLSModeIP | typeof TLSModeManual | typeof TLSModeOff;
/**
 * AlertCode names a dashboard alert (04 §11.4); 05 renders it from its catalog with Alert.Params.
 */
export const AlertCodeTransfer80 = "transfer.80";
export const AlertCodeTransfer100 = "transfer.100";
export const AlertCodeReleaseUpdate = "release.update";
export const AlertCodeReleaseSecurityUpdate = "release.security_update";
export const AlertCodePublicIPChanged = "public_ip.changed";
export const AlertCodeTLSRenewalFailing = "tls.renewal_failing";
export const AlertCodeDoctorFail = "doctor.fail";
export const AlertCodeDashboardSourceFailed = "dashboard.source_failed";
export type AlertCode = typeof AlertCodeTransfer80 | typeof AlertCodeTransfer100 | typeof AlertCodeReleaseUpdate | typeof AlertCodeReleaseSecurityUpdate | typeof AlertCodePublicIPChanged | typeof AlertCodeTLSRenewalFailing | typeof AlertCodeDoctorFail | typeof AlertCodeDashboardSourceFailed;
/**
 * AlertSeverity is how prominently the dashboard shows an alert.
 */
export const AlertSeverityInfo = "info";
export const AlertSeverityWarn = "warn";
export const AlertSeverityError = "error";
export type AlertSeverity = typeof AlertSeverityInfo | typeof AlertSeverityWarn | typeof AlertSeverityError;
/**
 * OpsDashboard is GET /api/v1/admin/dashboard (04 §11.4). A failing source yields an empty section (an empty list,
 * zero totals, or an absent pointer) plus an alert dashboard.source_failed, never a failed response.
 */
export interface OpsDashboard {
  generatedAt: string;
  server: ServerInfo;
  transfer: TransferInfo;
  media: MediaTotals;
  rooms: RoomLive[];
  clients: ClientVersionCount[];
  doctor?: DoctorSummary; // absent until the first doctor run
  alerts: Alert[];
  accounts?: DashboardAccounts; // 03's part; absent when its source failed
}
/**
 * ServerInfo is OpsDashboard.Server.
 */
export interface ServerInfo {
  version: string;
  startedAt: string;
  origin: string;
  process: ProcessInfo;
  tls: TLSInfo;
  publicIpv4: string; // "" when none is known
  publicIpv6: string;
  nat: NATKind;
  advertised: AdvertisedAddr[];
  update?: UpdateInfo; // absent before the first release check or when it is off
}
/**
 * ProcessInfo is ServerInfo.Process.
 */
export interface ProcessInfo {
  cpuSeconds: number /* float64 */;
  rssBytes: number /* int64 */;
  numCpu: number /* int */;
  goroutines: number /* int */;
}
/**
 * TLSInfo is the certificate state (04 §8.2 tlsmgr.Status without the English error text).
 */
export interface TLSInfo {
  mode: TLSMode;
  names: string[];
  ready: boolean;
  issuer?: string;
  notBefore?: string;
  notAfter?: string;
  nextRenewal?: string;
  lastErrorCode?: string; // an ACME hint code of 04 §8.7, e.g. "tls.dns_wrong"
  lastErrorAt?: string;
}
/**
 * AdvertisedAddr is one address the server advertises in ICE candidates.
 */
export interface AdvertisedAddr {
  proto: string; // "udp" | "tcp"
  addr: string; // host:port
  via: Transport;
}
/**
 * UpdateInfo is the result of the daily release check (04 §11.5).
 */
export interface UpdateInfo {
  latest: string;
  url: string;
  security: boolean; // a newer release is marked as a security release
  checkedAt: string;
}
/**
 * TransferInfo is month-to-date transfer, counted at the socket layer, per calendar month in UTC (04 §11.3).
 */
export interface TransferInfo {
  month: string; // "2026-09"
  egressBytes: number /* int64 */;
  ingressBytes: number /* int64 */;
  alertGb: number /* int */; // the setting transferAlertGb; 0 = off
  projectedEgressBytes?: number /* int64 */; // shown after day 3 of the month
  egressBps: number /* int64 */;
  ingressBps: number /* int64 */;
}
/**
 * MediaTotals is OpsDashboard.Media, from the SFU's totals (probe PCs excluded).
 */
export interface MediaTotals {
  ingressBps: number /* int64 */;
  egressBps: number /* int64 */;
  downTracks: number /* int */;
  peerConnections: TransportCounts;
}
/**
 * TransportCounts counts peer connections by selected transport.
 */
export interface TransportCounts {
  udp: number /* int */;
  tcp443: number /* int */;
  tcp7882: number /* int */;
}
/**
 * RoomLive is one room with its live participants and shares.
 */
export interface RoomLive {
  id: string;
  name: string;
  participants: ParticipantLive[];
  shares: ShareLive[];
}
/**
 * ParticipantLive is one user in a room.
 */
export interface ParticipantLive {
  userId: string;
  username: string;
  connections: ConnectionLive[];
  watching: string[]; // share IDs this user subscribes to
}
/**
 * ConnectionLive is one signaling connection. Transport and RTTMs come from the SFU, the rest from the hub.
 */
export interface ConnectionLive {
  id: string;
  kind: string; // 01's ClientKind
  role: string; // 01's Role
  version: string; // client version
  os: string;
  transport?: Transport; // absent until a PC has a selected pair
  rttMs: number /* int */;
  connectedAt: string;
}
/**
 * ShareLive is one share as the SFU sees it. Share labels are not shown.
 */
export interface ShareLive {
  shareId: string;
  ownerUserId: string;
  kind: string; // 01's share source kind, e.g. "window"
  startedAt: string;
  codec: string; // "h264/" + profile, e.g. "h264/640c"
  layers: LayerLive[];
  viewers: ViewerCounts;
  ingressBps: number /* int64 */;
  egressBps: number /* int64 */;
}
/**
 * LayerLive is one simulcast layer of a share.
 */
export interface LayerLive {
  rid: string; // "f" | "q"
  width: number /* int */;
  height: number /* int */;
  fps: number /* float64 */;
  bitrate: number /* int64 */; // bits/s
  lossPct: number /* float64 */;
}
/**
 * ViewerCounts counts a share's viewers by forwarded quality.
 */
export interface ViewerCounts {
  high: number /* int */;
  low: number /* int */;
  audio: number /* int */;
}
/**
 * ClientVersionCount counts connected clients per kind and version.
 */
export interface ClientVersionCount {
  kind: string;
  version: string;
  count: number /* int */;
  outdated: boolean; // below minClientVersion or older than this server
}
/**
 * DoctorSummary is OpsDashboard.Doctor: the counts of the last doctor run.
 */
export interface DoctorSummary {
  ranAt: string;
  ok: number /* int */;
  warn: number /* int */;
  fail: number /* int */;
}
/**
 * Alert is one dashboard alert.
 */
export interface Alert {
  code: AlertCode;
  severity: AlertSeverity;
  params?: { [key: string]: any};
}
/**
 * ServerStatus is the admin socket's GET /v1/status (04 §12.2, isshoni admin status --json) and doctor's view of a
 * running server (doctor.Env.Live): version, uptime, site, TLS, public addresses, listeners, live counts, schema
 * version, and the live state that only the running process knows and doctor's checks need: the public IP detection
 * (public_ip, 04 §7.4 netx.PublicAddrs), the effective media socket buffers (udp_buffers, 04 §7.3 netx.Transport),
 * and the transfer and release state (transfer, release).
 */
export interface ServerStatus {
  version: string;
  startedAt: string;
  uptimeS: number /* int64 */;
  origin: string;
  tls: TLSInfo;
  publicIpv4: string;
  publicIpv6: string;
  /**
   * PublicIPv4Method and PublicIPv6Method say how netx found each address (netx.Method): "config", "interface",
   * "stun" or "none".
   */
  publicIpv4Method?: string;
  publicIpv6Method?: string;
  /**
   * LocalIPv4 is the IPv4 of the default-route interface (netx.PublicAddrs.LocalV4; may equal PublicIPv4), the
   * {local} of public_ip's port_forward fix text.
   */
  localIpv4?: string;
  nat: NATKind;
  advertised: AdvertisedAddr[];
  listeners: ListenerInfo[];
  /**
   * UDPRcvBufBytes and UDPSndBufBytes are the effective SO_RCVBUF and SO_SNDBUF of the media sockets, read back
   * with getsockopt (netx.Transport.RcvBuf and SndBuf); absent when UDP is off.
   */
  udpRcvBufBytes?: number /* int */;
  udpSndBufBytes?: number /* int */;
  rooms: number /* int */;
  participants: number /* int */;
  shares: number /* int */;
  schemaVersion: number /* int */;
  transfer?: TransferInfo;
  update?: UpdateInfo;
}
/**
 * ListenerInfo is one bound listener of a running server.
 */
export interface ListenerInfo {
  key: string; // its config key: listen.https, listen.http, listen.ice_udp, listen.ice_tcp, metrics.listen, listen.admin_socket
  network: string; // "tcp" | "udp" | "unix"
  addr: string; // the bound address or socket path
}

//////////
// source: push.go

/**
 * PushPayloadVersion is PushPayload.V.
 */
export const PushPayloadVersion = 1;
/**
 * PushType is PushPayload.Type.
 */
export const PushTypeShareStarted = "share.started"; // a share went live (not a replacement); TTL 600 s, urgency high
export const PushTypeAdminAlert = "admin.alert"; // an admin alert; TTL 86400 s, urgency normal
export const PushTypeTest = "push.test"; // POST /api/v1/push/test; TTL 60 s, urgency high
export type PushType = typeof PushTypeShareStarted | typeof PushTypeAdminAlert | typeof PushTypeTest;
/**
 * AdminAlertKind is the kind of an admin alert (03 §7.11, plus 04's transfer_threshold). The service worker renders
 * it from push.adminAlert.<kind>.
 */
export const AdminAlertKindAdminGranted = "admin_granted";
export const AdminAlertKindAdminRevoked = "admin_revoked";
export const AdminAlertKindAdminPasswordReset = "admin_password_reset";
export const AdminAlertKindRegistrationModeChanged = "registration_mode_changed";
export const AdminAlertKindSignupPending = "signup_pending";
export const AdminAlertKindSecretsRotated = "secrets_rotated";
export const AdminAlertKindTransferThreshold = "transfer_threshold"; // Target is "80" or "100"
export const AdminAlertKindRefreshTokenReused = "refresh_token_reused"; // later (M2)
export type AdminAlertKind = typeof AdminAlertKindAdminGranted | typeof AdminAlertKindAdminRevoked | typeof AdminAlertKindAdminPasswordReset | typeof AdminAlertKindRegistrationModeChanged | typeof AdminAlertKindSignupPending | typeof AdminAlertKindSecretsRotated | typeof AdminAlertKindTransferThreshold | typeof AdminAlertKindRefreshTokenReused;
/**
 * PushPayload is the JSON a push message carries. The fields after URL depend on Type.
 */
export interface PushPayload {
  v: number /* int */; // PushPayloadVersion
  type: PushType;
  ts: number /* int64 */; // unix milliseconds
  tag: string; // a newer notification with the same tag replaces the older one
  url: string; // an SPA route, e.g. "/r/lounge?focus=s_q7m2x9c4v8b1n5k3"
  /**
   * share.started
   */
  room?: NameRef;
  user?: NameRef; // the sharer; Name is the username
  shareId?: string;
  /**
   * admin.alert
   */
  kind?: AdminAlertKind;
  actor?: string; // a username, "cli" or "system"
  target?: string; // a username, a threshold, or absent
}
/**
 * NameRef is {id, name}: PushPayload.Room and PushPayload.User.
 */
export interface NameRef {
  id: string;
  name: string;
}

//////////
// source: secret.go


//////////
// source: types.go

/**
 * Role is a user's role (03 §7.11).
 */
export const RoleAdmin = "admin";
export const RoleUser = "user";
export type Role = typeof RoleAdmin | typeof RoleUser;
/**
 * UserStatus is a user's account status. RegisterResponse uses active and pending.
 */
export const UserStatusActive = "active";
export const UserStatusPending = "pending";
export const UserStatusDisabled = "disabled";
export type UserStatus = typeof UserStatusActive | typeof UserStatusPending | typeof UserStatusDisabled;
/**
 * RegistrationMode is the setting registration.mode (03 §7.9).
 */
export const RegistrationModeInvite = "invite";
export const RegistrationModeApproval = "approval";
export const RegistrationModeClosed = "closed";
export type RegistrationMode = typeof RegistrationModeInvite | typeof RegistrationModeApproval | typeof RegistrationModeClosed;
/**
 * CreatedVia says how an account was created (AdminUser.CreatedVia).
 */
export const CreatedViaSetup = "setup";
export const CreatedViaInvite = "invite";
export const CreatedViaSignup = "signup";
export const CreatedViaCLI = "cli"; // reserved (03 §5)
export type CreatedVia = typeof CreatedViaSetup | typeof CreatedViaInvite | typeof CreatedViaSignup | typeof CreatedViaCLI;
/**
 * InviteState is an invite's state; inactive invites stay listed for 30 days.
 */
export const InviteStateActive = "active";
export const InviteStateExpired = "expired";
export const InviteStateUsedUp = "used_up";
export const InviteStateRevoked = "revoked";
export type InviteState = typeof InviteStateActive | typeof InviteStateExpired | typeof InviteStateUsedUp | typeof InviteStateRevoked;
/**
 * ShareStartedPref is the push preference shareStarted (03 §12.4.6).
 */
export const ShareStartedPrefAll = "all";
export const ShareStartedPrefOff = "off";
export type ShareStartedPref = typeof ShareStartedPrefAll | typeof ShareStartedPrefOff;
/**
 * AuditOutcome is an audit row's outcome (03 §5).
 */
export const AuditOutcomeOK = "ok";
export const AuditOutcomeDenied = "denied";
export type AuditOutcome = typeof AuditOutcomeOK | typeof AuditOutcomeDenied;
/**
 * User is the public identity shape {id, username, role} that other docs reuse (login, register, setup and reset
 * replies, Me). CreatedAt is set only in Me.
 */
export interface User {
  id: string;
  username: string;
  role: Role;
  createdAt?: string;
}
/**
 * UserRef names a user: an invite's creator and redeemers, AdminUser.InvitedBy.
 */
export interface UserRef {
  id: string;
  username: string;
}
/**
 * Empty is the body of requests and replies without fields: {}.
 */
export interface Empty {
}
/**
 * UserResponse is {user}: login (#2), setup/complete (#8), reset/complete (#10).
 */
export interface UserResponse {
  user: User;
}
export const InfoFeaturePush = "push"; // present exactly when Info.Push is present
export const InfoFeaturePasswordReset = "passwordReset"; // M1
export const InfoFeatureDeviceFlow = "deviceFlow"; // later (M2)
/**
 * Info feature strings (Info.Features). The set is open: clients ignore unknown values.
 */
export type InfoFeature = typeof InfoFeaturePush | typeof InfoFeaturePasswordReset | typeof InfoFeatureDeviceFlow;
/**
 * Info is GET /api/v1/info (#1, 03 §12.4.1).
 */
export interface Info {
  server: InfoServer;
  protocol: InfoProtocol; // from internal/protocol (01)
  minClientVersion: string; // "" = no floor
  registration: RegistrationMode;
  setupRequired: boolean;
  features: string[]; // InfoFeature* values
  accountRules: AccountRules;
  push?: InfoPush; // absent when push is unavailable
}
/**
 * InfoServer is Info.Server.
 */
export interface InfoServer {
  name: string; // the setting serverName, or else the host of the primary origin
  version: string;
  publicUrl: string;
}
/**
 * InfoProtocol is Info.Protocol: the signaling protocol versions this server speaks.
 */
export interface InfoProtocol {
  current: number /* int */;
  min: number /* int */;
}
/**
 * AccountRules are the form rules the SPA shows and checks before submitting.
 */
export interface AccountRules {
  usernameMinLength: number /* int */;
  usernameMaxLength: number /* int */;
  passwordMinLength: number /* int */;
  passwordMaxLength: number /* int */;
}
/**
 * InfoPush is Info.Push.
 */
export interface InfoPush {
  vapidPublicKey: string; // base64url, uncompressed P-256 point
}
/**
 * LoginRequest is POST /api/v1/auth/login (#2); the reply is UserResponse.
 */
export interface LoginRequest {
  username: string;
  password: string;
}
/**
 * RegisterRequest is POST /api/v1/auth/register (#5).
 */
export interface RegisterRequest {
  inviteToken?: string; // absent: a public sign-up (approval mode only)
  username: string;
  password: string;
}
/**
 * RegisterResponse is the reply to #5: 201 {status: "active", user} with the cookie, or 202 {status: "pending"}.
 */
export interface RegisterResponse {
  status: UserStatus;
  user?: User;
}
/**
 * TokenRequest is the {token} body of auth/invite/check (#6), auth/setup/check (#7) and auth/reset/check (#9).
 */
export interface TokenRequest {
  token: string;
}
/**
 * InviteInfo is the reply to POST /api/v1/auth/invite/check (#6).
 */
export interface InviteInfo {
  serverName: string;
  /**
   * InvitedBy is the creator's username. It is absent when the invite was created from the CLI or its creator was
   * deleted (invites.created_by is NULL, 03 §5), like Invite.CreatedBy.
   */
  invitedBy?: string;
  expiresAt: string;
  usesLeft: number /* int */;
}
/**
 * SetupCompleteRequest is POST /api/v1/auth/setup/complete (#8); the reply is UserResponse.
 */
export interface SetupCompleteRequest {
  token: string;
  username: string;
  password: string;
  serverName?: string;
}
/**
 * ResetCheckResponse is the reply to POST /api/v1/auth/reset/check (#9).
 */
export interface ResetCheckResponse {
  username: string;
}
/**
 * ResetCompleteRequest is POST /api/v1/auth/reset/complete (#10); the reply is UserResponse.
 */
export interface ResetCompleteRequest {
  token: string;
  password: string;
}
/**
 * Me is GET /api/v1/me (#11, 03 §12.4.3).
 */
export interface Me {
  user: User;
  session?: SessionInfo; // the caller's web session (always set in M1)
  device?: DeviceInfo; // later (M2): a bearer principal gets its device instead
  permissions: Permissions;
  badges?: Badges; // admins only
}
/**
 * Permissions is Me.Permissions.
 */
export interface Permissions {
  admin: boolean;
  createInvites: boolean; // admins, or members while membersCanInvite is on
}
/**
 * Badges is Me.Badges: counts for the admin navigation.
 */
export interface Badges {
  pendingApprovals: number /* int */;
}
/**
 * SessionInfo is one web session: Me.Session (with expiresAt) and the items of GET /api/v1/me/sessions (with
 * lastSeenAt and lastIp).
 */
export interface SessionInfo {
  id: string;
  name: string; // from the User-Agent, e.g. "Chrome on Windows"
  createdAt: string;
  expiresAt?: string;
  lastSeenAt?: string;
  lastIp?: string;
  current: boolean; // this request's session
}
/**
 * DeviceInfo is one linked app: the items of GET /api/v1/me/devices (#17, empty until M2) and, later (M2), Me.Device
 * with only id, name and clientKind.
 */
export interface DeviceInfo {
  id: string;
  name: string;
  clientKind: string; // 01's ClientKind: desktop | mobile
  os?: string;
  appVersion?: string;
  createdAt?: string;
  lastSeenAt?: string;
  lastIp?: string;
}
/**
 * ChangePasswordRequest is POST /api/v1/me/password (#12); the reply is Empty.
 */
export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}
/**
 * DeleteSelfRequest is POST /api/v1/me/delete (#13).
 */
export interface DeleteSelfRequest {
  password: string;
}
/**
 * SessionsResponse is GET /api/v1/me/sessions (#14).
 */
export interface SessionsResponse {
  sessions: SessionInfo[];
}
/**
 * RevokeOthersResponse is the reply to POST /api/v1/me/sessions/revoke-others (#16).
 */
export interface RevokeOthersResponse {
  revoked: number /* int */;
}
/**
 * DevicesResponse is GET /api/v1/me/devices (#17).
 */
export interface DevicesResponse {
  devices: DeviceInfo[];
}
/**
 * Rooms is GET /api/v1/rooms (#19, 03 §12.4.4).
 */
export interface Rooms {
  defaultRoomId: string;
  showRoomList: boolean; // more than one room exists
  rooms: Room[];
}
/**
 * Room is one room. Live counts come from the signaling hub and are never stored.
 */
export interface Room {
  id: string;
  name: string;
  isDefault: boolean;
  createdAt: string;
  live: RoomPresence;
}
/**
 * RoomPresence is Room.Live.
 */
export interface RoomPresence {
  participants: number /* int */;
  shares: number /* int */;
}
/**
 * CreateRoomRequest is POST /api/v1/admin/rooms (#37); the reply is RoomResponse.
 */
export interface CreateRoomRequest {
  name: string;
}
/**
 * PatchRoomRequest is PATCH /api/v1/admin/rooms/{id} (#38), a JSON merge; the reply is RoomResponse.
 */
export interface PatchRoomRequest {
  name?: string;
}
/**
 * RoomResponse is {room}: the reply to #37 and #38.
 */
export interface RoomResponse {
  room: Room;
}
/**
 * Invite is one invite link's metadata (03 §12.4.5). The token itself is returned only once, in
 * CreateInviteResponse.URL.
 */
export interface Invite {
  id: string;
  note: string;
  createdBy?: UserRef; // absent when created by the CLI or the creator was deleted
  createdAt: string;
  expiresAt: string;
  maxUses: number /* int */;
  uses: number /* int */;
  state: InviteState;
  redeemedBy: UserRef[];
}
/**
 * CreateInviteRequest is POST /api/v1/invites (#22). Every field is optional; 0 means the setting's default.
 */
export interface CreateInviteRequest {
  note?: string;
  expiresInHours?: number /* int */; // 1–720
  maxUses?: number /* int */; // 1–1000
}
/**
 * CreateInviteResponse is the reply to #22.
 */
export interface CreateInviteResponse {
  invite: Invite;
  url: string; // <primary origin>/invite#<token>
}
/**
 * InvitesResponse is GET /api/v1/invites?state=active|all (#21).
 */
export interface InvitesResponse {
  invites: Invite[];
}
/**
 * PushSubscribeRequest is POST /api/v1/push/subscriptions (#24): the browser's PushSubscription.toJSON(), trimmed.
 */
export interface PushSubscribeRequest {
  endpoint: string;
  keys: PushKeys;
}
/**
 * PushKeys is PushSubscribeRequest.Keys (base64url).
 */
export interface PushKeys {
  p256dh: string; // 65 bytes, starting with 0x04
  auth: string; // 16 bytes
}
/**
 * PushSubscribeResponse is the reply to #24: 201 when new, 200 when the endpoint was known.
 */
export interface PushSubscribeResponse {
  id: string;
}
/**
 * PushUnsubscribeRequest is POST /api/v1/push/unsubscribe (#27).
 */
export interface PushUnsubscribeRequest {
  endpoint: string;
}
/**
 * PushPreferences is GET and PUT /api/v1/push/preferences (#50, #51).
 */
export interface PushPreferences {
  shareStarted: ShareStartedPref; // default all
  adminAlerts: boolean; // default true; matters for admins only
}
/**
 * AdminUser is one row of GET /api/v1/admin/users (#29) and the reply of #30 and #35. It has no IPs.
 */
export interface AdminUser {
  id: string;
  username: string;
  role: Role;
  status: UserStatus;
  createdVia: CreatedVia;
  createdAt: string;
  lastLoginAt?: string;
  lastSeenAt?: string; // latest over sessions and devices
  invitedBy?: UserRef; // the creator of the invite this user redeemed
  sessions: number /* int */;
  devices: number /* int */;
  online: boolean; // from the signaling hub
  resetPending: boolean;
}
/**
 * AdminUsersResponse is GET /api/v1/admin/users?status=active|pending|disabled (#29).
 */
export interface AdminUsersResponse {
  users: AdminUser[];
}
/**
 * AdminUserResponse is {user}: the reply to PATCH /api/v1/admin/users/{id} (#30) and to approve (#35).
 */
export interface AdminUserResponse {
  user: AdminUser;
}
/**
 * PatchUserRequest is PATCH /api/v1/admin/users/{id} (#30), a JSON merge. CurrentPassword is needed only when Role
 * becomes admin; Status accepts only active or disabled.
 */
export interface PatchUserRequest {
  username?: string;
  role?: Role;
  status?: UserStatus;
  currentPassword?: string;
}
/**
 * PasswordResetRequest is POST /api/v1/admin/users/{id}/password-reset (#32); CurrentPassword is needed only when
 * the target is an admin. The reply is ResetLink.
 */
export interface PasswordResetRequest {
  currentPassword?: string;
}
/**
 * ResetLink is the reply to #32: a one-time password-reset link.
 */
export interface ResetLink {
  url: string; // <primary origin>/reset#<token>
  expiresAt: string;
}
/**
 * SignOutResponse is the reply to POST /api/v1/admin/users/{id}/sign-out (#33).
 */
export interface SignOutResponse {
  sessions: number /* int */;
  devices: number /* int */;
}
/**
 * PendingUser is one sign-up in the approval queue.
 */
export interface PendingUser {
  id: string;
  username: string;
  requestedAt: string;
  ip: string; // the sign-up IP, from the audit row
}
/**
 * ApprovalsResponse is GET /api/v1/admin/approvals (#34).
 */
export interface ApprovalsResponse {
  pending: PendingUser[];
}
/**
 * RejectRequest is the body of POST /api/v1/admin/approvals/{id}/reject (#36). With {id} = "all", All must be true.
 */
export interface RejectRequest {
  all?: boolean;
}
/**
 * RejectAllResponse is the reply to #36 in its "all" form.
 */
export interface RejectAllResponse {
  rejected: number /* int */;
}
/**
 * Settings mirrors store.Settings (03 §9): the runtime settings with their JSON names, which are also the names in
 * SettingsResponse.Locked and in setting_locked's params.field.
 */
export interface Settings {
  serverName: string;
  registrationMode: RegistrationMode;
  inviteDefaultTtlHours: number /* int */;
  inviteDefaultMaxUses: number /* int */;
  membersCanInvite: boolean;
  maxParticipantsPerRoom: number /* int */; // 0 = no limit
  maxSharesPerRoom: number /* int */; // 0 = no limit
  maxShareBitrateKbps: number /* int */; // 0 = preset default
  transferAlertGb: number /* int */; // 0 = off; 1 GB = 10⁹ bytes
  updateCheck: boolean;
  minClientVersion: string; // "" or SemVer
  setupWizardDone: boolean;
}
/**
 * SettingsResponse is GET and PATCH /api/v1/admin/settings (#40, #41). The PATCH body is a partial Settings.
 */
export interface SettingsResponse {
  settings: Settings;
  defaults: Settings;
  locked: string[]; // JSON names pinned by config
}
/**
 * AuditEntry is one audit-log row (03 §10). Names are snapshots taken when the row was written.
 */
export interface AuditEntry {
  id: number /* int64 */; // the pagination cursor
  at: string;
  action: string; // e.g. "user.role_changed" (03 §10)
  outcome: AuditOutcome;
  actor: AuditRef;
  target?: AuditRef; // absent when the action has no target
  ip?: string;
  detail: { [key: string]: any}; // small, never secrets; {} when empty
}
/**
 * AuditRef is an audit row's actor or target. Actor kinds: user, cli, system, anonymous. Target kinds: user,
 * session, device, invite, room, settings, setup.
 */
export interface AuditRef {
  kind: string;
  id?: string;
  name?: string;
}
/**
 * AuditPage is GET /api/v1/admin/audit?before&limit&action&actor&target (#42). NextBefore is always present and null
 * on the last page; its tstype tag makes tygo emit `nextBefore: number | null` instead of an optional field.
 */
export interface AuditPage {
  entries: AuditEntry[];
  nextBefore: number | null; // null on the last page
}
/**
 * DashboardAccounts is the accounts part of 04's admin dashboard (03 §12.4.8), built by httpapi's
 * (*API).DashboardAccounts.
 */
export interface DashboardAccounts {
  users: DashboardUserCounts;
  invites: DashboardInviteCounts;
  sessions: DashboardSessionCounts;
  devices: DashboardDeviceCounts;
  registrationMode: RegistrationMode;
  securityEvents: AuditEntry[]; // ≤ 20 security-flagged rows of the last 7 days
}
/**
 * DashboardUserCounts is DashboardAccounts.Users.
 */
export interface DashboardUserCounts {
  active: number /* int */;
  pending: number /* int */;
  disabled: number /* int */;
  admins: number /* int */;
}
/**
 * DashboardInviteCounts is DashboardAccounts.Invites.
 */
export interface DashboardInviteCounts {
  active: number /* int */;
}
/**
 * DashboardSessionCounts is DashboardAccounts.Sessions.
 */
export interface DashboardSessionCounts {
  active: number /* int */;
}
/**
 * DashboardDeviceCounts is DashboardAccounts.Devices.
 */
export interface DashboardDeviceCounts {
  linked: number /* int */;
}

//////////
// source: wiretime.go

/**
 * WireTime is a timestamp in the one JSON form of the API (03 §3.3): an RFC 3339 UTC string with exactly three
 * fractional digits and a Z suffix, "2026-09-30T12:00:00.000Z", whatever the location and precision of the value
 * (the fraction is truncated to the millisecond, not rounded). It is the fixed-width form of 01's signaling
 * timestamps (01 §5, internal/protocol) and of JavaScript's Date.toISOString, so the strings also sort as text.
 * DTO fields stay time.Time, which tygo maps to string: the MarshalJSON methods in encode.go encode each of them as a
 * WireTime, so every encoder sends this form. Code that writes a timestamp into JSON outside these DTOs (04's admin
 * socket, for example) declares the field as WireTime. Decoding accepts any RFC 3339 form, as time.Time does, and
 * keeps the value as sent.
 */
export type WireTime = string;
