// Code generated by tsregistry from protocol.Registry (internal/protocol/registry.go). DO NOT EDIT.
// Regenerate with "task gen" (docs/m1/01-protocol.md §14.4). The payload types are tygo's, in types.gen.ts.

import type * as P from './types.gen';

/**
 * Client→server requests (01 §7): each carries an id and gets exactly one reply, an error or a message of type reply
 * (ok, or welcome for hello) with the payload result. SignalClient.request sends data and resolves with result; the
 * SignalClient sends hello itself.
 */
export interface ClientRequests {
  hello: { data: P.Hello; result: P.Welcome; reply: 'welcome' };
  'room.join': { data: P.RoomJoin; result: P.RoomJoinResult; reply: 'ok' };
  'room.leave': { data: P.Empty; result: P.Empty; reply: 'ok' };
  /** Roles: full, publisher, agent. */
  'share.start': { data: P.ShareStart; result: P.ShareParams; reply: 'ok' };
  /** Roles: full, publisher, agent. */
  'share.update': { data: P.ShareUpdate; result: P.ShareParams; reply: 'ok' };
  /** Roles: full, publisher, agent. */
  'share.stop': { data: P.ShareStop; result: P.Empty; reply: 'ok' };
  /** Roles: full, viewer. */
  'subscribe.update': { data: P.SubscribeUpdate; result: P.SubscribeResult; reply: 'ok' };
  'stats.watch': { data: P.StatsWatch; result: P.Empty; reply: 'ok' };
  /** Feature agent.relay. */
  'agent.send': { data: P.AgentSend; result: P.AgentSendResult; reply: 'ok' };
}

/** Client→server notifications (no id, no reply): the payload per type, as SignalClient.notify sends it. */
export interface ClientNotifications {
  ping: P.Ping;
  'pc.offer': P.PCOffer;
  'pc.answer': P.PCAnswer;
  'pc.ice': P.PCICE;
  'pc.restart': P.PCRestart;
  'pc.close': P.PCClose;
  'caps.update': P.CapsUpdate;
  stats: P.ClientStats;
}

/**
 * Server→client messages, replies and notifications: the payload per type. ok carries the result of the request it
 * answers (ClientRequests[type]['result']); error is a reply when it has a re, else a notification (01 §8.13).
 * Clients ignore types they do not know.
 */
export interface ServerMessages {
  welcome: P.Welcome;
  ok: P.RoomJoinResult | P.Empty | P.ShareParams | P.SubscribeResult | P.AgentSendResult;
  error: P.Error;
  pong: P.Pong;
  'room.state': P.RoomState;
  'room.event': P.RoomEvent;
  'pc.offer': P.PCOffer;
  'pc.answer': P.PCAnswer;
  'pc.ice': P.PCICE;
  'pc.restart': P.PCRestart;
  'subscribe.status': P.SubscribeStatus;
  'quality.hint': P.QualityHint;
  stats: P.ServerStats;
  invalidate: P.Invalidate;
  'server.shutdown': P.ServerShutdown;
  /** Feature agent.relay. */
  'agent.recv': P.AgentRecv;
  /** Milestone M2. Feature user.connections. */
  'user.connections': P.UserConnections;
}

export type ClientRequestType = keyof ClientRequests;
export type ClientNotificationType = keyof ClientNotifications;
export type ClientMessageType = ClientRequestType | ClientNotificationType;
export type ServerMessageType = keyof ServerMessages;

/**
 * A server→client message, discriminated by type. re is set on replies. data is always set: an absent data means {}
 * on the wire (01 §5), and the SignalClient fills it in.
 */
export type ServerEnvelope<K extends ServerMessageType = ServerMessageType> = {
  [T in K]: { type: T; re?: string; data: ServerMessages[T] };
}[K];

/**
 * A client→server message, discriminated by type: requests carry an id (1–32 chars [A-Za-z0-9_-], unique among the
 * client's outstanding requests), notifications none.
 */
export type ClientEnvelope<K extends ClientMessageType = ClientMessageType> = {
  [T in K]: T extends ClientRequestType
    ? { type: T; id: string; data: ClientRequests[T]['data'] }
    : T extends ClientNotificationType
      ? { type: T; data: ClientNotifications[T] }
      : never;
}[K];

/** Client→server request types. */
export const clientRequestTypes = [
  'hello',
  'room.join',
  'room.leave',
  'share.start',
  'share.update',
  'share.stop',
  'subscribe.update',
  'stats.watch',
  'agent.send',
] as const satisfies readonly P.MessageType[];

/** Client→server notification types. */
export const clientNotificationTypes = [
  'ping',
  'pc.offer',
  'pc.answer',
  'pc.ice',
  'pc.restart',
  'pc.close',
  'caps.update',
  'stats',
] as const satisfies readonly P.MessageType[];

/** Server→client message types (replies and notifications). */
export const serverMessageTypes = [
  'welcome',
  'ok',
  'error',
  'pong',
  'room.state',
  'room.event',
  'pc.offer',
  'pc.answer',
  'pc.ice',
  'pc.restart',
  'subscribe.status',
  'quality.hint',
  'stats',
  'invalidate',
  'server.shutdown',
  'agent.recv',
  'user.connections',
] as const satisfies readonly P.MessageType[];

/** Every message type, both directions. */
export const messageTypes = [
  'hello',
  'ping',
  'room.join',
  'room.leave',
  'share.start',
  'share.update',
  'share.stop',
  'pc.offer',
  'pc.answer',
  'pc.ice',
  'pc.restart',
  'pc.close',
  'subscribe.update',
  'caps.update',
  'stats',
  'stats.watch',
  'agent.send',
  'welcome',
  'ok',
  'error',
  'pong',
  'room.state',
  'room.event',
  'subscribe.status',
  'quality.hint',
  'invalidate',
  'server.shutdown',
  'agent.recv',
  'user.connections',
] as const satisfies readonly P.MessageType[];

/** The reply type of each request: ok, or welcome for hello. */
export const requestReplies: { readonly [K in ClientRequestType]: ClientRequests[K]['reply'] } = {
  hello: 'welcome',
  'room.join': 'ok',
  'room.leave': 'ok',
  'share.start': 'ok',
  'share.update': 'ok',
  'share.stop': 'ok',
  'subscribe.update': 'ok',
  'stats.watch': 'ok',
  'agent.send': 'ok',
};

/**
 * The feature each message type behind one needs (01 §6.2); the others are baseline. A feature is active only when
 * welcome.features lists it.
 */
export const messageFeatures: Readonly<Partial<Record<P.MessageType, P.Feature>>> = {
  'agent.send': 'agent.relay',
  'agent.recv': 'agent.relay',
  'user.connections': 'user.connections',
};
