// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/protocol. DO NOT EDIT.

//////////
// source: agent.go

/**
 * AgentSend relays an opaque payload to other connections of the same user (01 §8.14, feature agent.relay). Only the
 * transport is defined in v1; the server never parses Payload.
 * Reserved kinds: share.request, share.status (M4); playback.stop, exclusions.get, exclusions.set (M2).
 */
export interface AgentSend {
  to?: string; // a connectionId of the same user, or
  toRole?: Role; // all the user's connections with this role (exactly one of To/ToRole)
  kind: string; // [a-z.]{1,32}; registry in 04/M2 docs
  payload: unknown; // <= 16 KiB, opaque to the server
}
/**
 * AgentSendResult is the ok payload of agent.send.
 */
export interface AgentSendResult {
  delivered: number /* int */;
}
/**
 * AgentRecv delivers a relayed payload.
 */
export interface AgentRecv {
  from: string; // the sender's connectionId
  kind: string;
  payload: unknown;
}
/**
 * UserConnections (later M2, feature user.connections): all of the user's connections, sent to each of them on change.
 */
export interface UserConnections {
  connections: OwnConnection[];
}
/**
 * OwnConnection is one of the user's own connections, with the details other users never see. The embedded
 * ConnectionInfo's fields are inlined in JSON; the tstype tag makes tygo emit "extends ConnectionInfo" to match.
 */
export interface OwnConnection extends ConnectionInfo {
  os: ClientOS;
  version: string;
  roomId?: string;
}

//////////
// source: codec.go

/**
 * CodecKey names a codec as clients report it: "opus", or "h264/<profile_idc><constraint byte>" in lowercase hex,
 * e.g. "h264/42e0" (constrained baseline), "h264/4200" (baseline), "h264/4d00" (main), "h264/640c" (constrained
 * high), "h264/6400" (high). The level is ignored (S4 finding 5: Chrome advertises High as 640034).
 * Declared with single-line consts (no const group) so tygo keeps it a plain string, not a closed union: clients may
 * report keys this build does not know.
 */
export type CodecKey = string;
export const CodecOpus: CodecKey = "opus";
export const CodecH264ConstrainedBaseline: CodecKey = "h264/42e0";
export const CodecH264Baseline: CodecKey = "h264/4200";
export const CodecH264Main: CodecKey = "h264/4d00";
export const CodecH264ConstrainedHigh: CodecKey = "h264/640c";
export const CodecH264High: CodecKey = "h264/6400";

//////////
// source: doc.go
/*
Package protocol is isshoni's signaling protocol, version 1 (docs/m1/01-protocol.md): the WebSocket envelope,
every message payload and enum, the error codes and close codes, the message registry, and payload validation.

It is the single source of truth for the wire format. The TypeScript types in web/src/protocol are generated from
it (tygo for the types, internal/protocol/gen/tsregistry for the registry; 01 §14.4), and the golden fixtures in
testdata/v1 pin the JSON shape of every message (01 §14.3).

The package imports only the standard library, so the server, the Go clients and the generator can all use it.

# Wire conventions (01 §5)

Every WebSocket text frame is one [Envelope] {type, id, re, data}. Keys are camelCase, unknown keys are ignored,
IDs are strings, units live in the field name (…Bitrate in bit/s, …Ms in milliseconds), timestamps are RFC 3339
UTC strings with millisecond precision, and arrays are always present ([] rather than null). The types' MarshalJSON
methods enforce the last two rules, so callers may leave slices nil.

# Compatibility (01 §14)

Within a protocol version every change is additive: new optional fields whose zero value means the old behavior,
new message types behind a feature, new server→client enum values with a client fallback, new error codes, new
features. Renaming or removing a field, changing its type, unit or meaning, or reusing an error code is forbidden.
The fixtures are copied to testdata/compat/<version> before each release, and the compat test decodes them with
the current code.

# Adding to this package

Enum constants use the <Type><Value> naming in one const group per type, so tygo turns them into TS union types;
CodecKey and AuthScheme use single-line constants on purpose so they stay plain strings in TS. A new message type
needs a Registry entry and a fixture; a new payload type with a slice field needs a MarshalJSON method in
encode.go (the no-null test finds a missing one); a new client→server payload needs a Validate method.
*/

/**
 * Protocol versions this build speaks (01 §6.1). The server accepts [MinVersion, Version]; once version 2 exists,
 * MinVersion stays at Version-1.
 */
export const Version = 1; // newest protocol version this build speaks
/**
 * Protocol versions this build speaks (01 §6.1). The server accepts [MinVersion, Version]; once version 2 exists,
 * MinVersion stays at Version-1.
 */
export const MinVersion = 1; // oldest version this build still speaks (Version-1 once Version >= 2)

//////////
// source: encode.go


//////////
// source: envelope.go

/**
 * MessageType is the envelope's type: dotted lowercase noun.verb (room.join), or a bare word for protocol-level
 * messages. One constant per row of the message catalog (01 §7).
 */
export const MessageTypeHello = "hello";
export const MessageTypeWelcome = "welcome";
export const MessageTypeOK = "ok";
export const MessageTypeError = "error";
export const MessageTypePing = "ping";
export const MessageTypePong = "pong";
export const MessageTypeRoomJoin = "room.join";
export const MessageTypeRoomLeave = "room.leave";
export const MessageTypeRoomState = "room.state";
export const MessageTypeRoomEvent = "room.event";
export const MessageTypeShareStart = "share.start";
export const MessageTypeShareUpdate = "share.update";
export const MessageTypeShareStop = "share.stop";
export const MessageTypePCOffer = "pc.offer";
export const MessageTypePCAnswer = "pc.answer";
export const MessageTypePCICE = "pc.ice";
export const MessageTypePCRestart = "pc.restart";
export const MessageTypePCClose = "pc.close";
export const MessageTypeSubscribeUpdate = "subscribe.update";
export const MessageTypeSubscribeStatus = "subscribe.status";
export const MessageTypeQualityHint = "quality.hint";
export const MessageTypeCapsUpdate = "caps.update";
export const MessageTypeStats = "stats"; // ClientStats from clients, ServerStats from the server
export const MessageTypeStatsWatch = "stats.watch";
export const MessageTypeInvalidate = "invalidate";
export const MessageTypeServerShutdown = "server.shutdown";
export const MessageTypeAgentSend = "agent.send";
export const MessageTypeAgentRecv = "agent.recv";
export const MessageTypeUserConnections = "user.connections"; // later (M2, feature user.connections)
export type MessageType = typeof MessageTypeHello | typeof MessageTypeWelcome | typeof MessageTypeOK | typeof MessageTypeError | typeof MessageTypePing | typeof MessageTypePong | typeof MessageTypeRoomJoin | typeof MessageTypeRoomLeave | typeof MessageTypeRoomState | typeof MessageTypeRoomEvent | typeof MessageTypeShareStart | typeof MessageTypeShareUpdate | typeof MessageTypeShareStop | typeof MessageTypePCOffer | typeof MessageTypePCAnswer | typeof MessageTypePCICE | typeof MessageTypePCRestart | typeof MessageTypePCClose | typeof MessageTypeSubscribeUpdate | typeof MessageTypeSubscribeStatus | typeof MessageTypeQualityHint | typeof MessageTypeCapsUpdate | typeof MessageTypeStats | typeof MessageTypeStatsWatch | typeof MessageTypeInvalidate | typeof MessageTypeServerShutdown | typeof MessageTypeAgentSend | typeof MessageTypeAgentRecv | typeof MessageTypeUserConnections;
/**
 * Envelope is every WebSocket message (01 §5).
 */
export interface Envelope {
  type: MessageType;
  id?: string; // requests only: 1-32 chars [A-Za-z0-9_-], chosen by the requester
  re?: string; // replies only: the id of the request this answers
  data?: unknown; // payload for Type; absent means {}
}
/**
 * Empty is the payload of requests and replies without fields.
 */
export interface Empty {
}

//////////
// source: errors.go

/**
 * Error is the payload of an error message (01 §8.13). It is a reply when Re is set on the envelope (scope request),
 * otherwise a notification. It carries codes, never English text; Params holds machine-readable values for i18n
 * interpolation. Its tstype tag types Params as unknown values in TypeScript, not any (tygo splits a tag at its
 * commas, so the tag spells Record<string, unknown> as an index signature).
 */
export interface Error {
  code: ErrorCode;
  retryable: boolean;
  scope: ErrorScope;
  retryAfterMs?: number /* int */;
  shareId?: string;
  roomId?: string;
  pc?: PCKind;
  gen?: number /* uint32 */;
  neg?: number /* uint32 */;
  params?: { [key: string]: unknown }; // machine-readable values for i18n interpolation; never prose
}
/**
 * ErrorScope says what an error affects, and so what an older client does with a code it doesn't know (01 §12.3).
 */
export const ErrorScopeRequest = "request"; // only the request `re` failed (never used for notifications)
export const ErrorScopeSubscription = "subscription"; // reserved: no M1 code uses it; subscribe.status reports subscriptions
export const ErrorScopeShare = "share"; // one of the user's shares failed or can't be published
export const ErrorScopePC = "pc"; // negotiation (pc, gen, neg) failed
export const ErrorScopeRoom = "room"; // the connection is no longer in the room
export const ErrorScopeConnection = "connection"; // the server closes the socket next; retryable = reconnect helps
export const ErrorScopeSession = "session"; // credentials are gone; go to the login page
export type ErrorScope = typeof ErrorScopeRequest | typeof ErrorScopeSubscription | typeof ErrorScopeShare | typeof ErrorScopePC | typeof ErrorScopeRoom | typeof ErrorScopeConnection | typeof ErrorScopeSession;
/**
 * ErrorCode is a stable snake_case error code (01 §12.1). A code is never renamed or reused with another meaning.
 * 05 maps each to errors.<code> in en.json. Codes shared with 03's REST table (bad_request, unauthenticated,
 * forbidden, rate_limited, internal, account_disabled, room_not_found, server_shutdown) mean the same in both.
 */
export const ErrorCodeBadMessage = "bad_message"; // frame isn't a JSON object, or the envelope is invalid
export const ErrorCodeHelloRequired = "hello_required"; // first message isn't hello
export const ErrorCodeHelloTimeout = "hello_timeout"; // no hello within 10 s
export const ErrorCodeIdleTimeout = "idle_timeout"; // no frame (message or pong) received for 45 s
export const ErrorCodeProtocolUnsupported = "protocol_unsupported"; // no common version; params {serverMin, serverMax, serverVersion}
export const ErrorCodeClientOutdated = "client_outdated"; // native client below minClientVersion
export const ErrorCodeUnauthenticated = "unauthenticated"; // no valid cookie and no valid bearer
export const ErrorCodeSessionRevoked = "session_revoked"; // every 03 revocation reason except account_disabled
export const ErrorCodeAccountDisabled = "account_disabled"; // admin disabled the account
export const ErrorCodeTooManyConnections = "too_many_connections"; // more than 16 connections for this user
export const ErrorCodeRateLimited = "rate_limited"; // a rate limit; retryAfterMs
export const ErrorCodeSlowConnection = "slow_connection"; // send queue overflow
export const ErrorCodeReplaced = "replaced"; // the same connection resumed on another socket
export const ErrorCodeServerShutdown = "server_shutdown"; // the hub is stopping (after server.shutdown)
export const ErrorCodeInternal = "internal"; // unexpected server error; params {ref}
export const ErrorCodeBadRequest = "bad_request"; // payload invalid; params {field, reason}
export const ErrorCodeUnknownType = "unknown_type"; // a request type the server doesn't know
export const ErrorCodeMessageTooLarge = "message_too_large"; // a non-SDP message over 64 KiB after hello; agent.send payload over 16 KiB
export const ErrorCodeForbidden = "forbidden"; // role, ownership or CanJoin check failed
export const ErrorCodeFeatureDisabled = "feature_disabled"; // a message behind a feature that isn't active
export const ErrorCodeNotInRoom = "not_in_room"; // share or PC message without a room
export const ErrorCodeRoomNotFound = "room_not_found"; // unknown, deleted or malformed room id
export const ErrorCodeRoomFull = "room_full"; // admin soft limit; params {limit}
export const ErrorCodeKicked = "kicked"; // later: reserved for an admin kick
export const ErrorCodeRoomClosed = "room_closed"; // an admin deleted the room
export const ErrorCodeShareNotFound = "share_not_found"; // share.update of an unknown share
export const ErrorCodeShareLimit = "share_limit"; // params {limit, per: "user"|"room"}
export const ErrorCodeCodecNotSupported = "codec_not_supported"; // publisher offered no usable H.264
export const ErrorCodeSDPInvalid = "sdp_invalid"; // SDP failed to apply (pc, gen, neg)
export const ErrorCodeStaleNegotiation = "stale_negotiation"; // pub offer with an older gen or neg (pc, gen, neg)
export const ErrorCodeAgentTargetNotFound = "agent_target_not_found"; // no same-user connection matches
export type ErrorCode = typeof ErrorCodeBadMessage | typeof ErrorCodeHelloRequired | typeof ErrorCodeHelloTimeout | typeof ErrorCodeIdleTimeout | typeof ErrorCodeProtocolUnsupported | typeof ErrorCodeClientOutdated | typeof ErrorCodeUnauthenticated | typeof ErrorCodeSessionRevoked | typeof ErrorCodeAccountDisabled | typeof ErrorCodeTooManyConnections | typeof ErrorCodeRateLimited | typeof ErrorCodeSlowConnection | typeof ErrorCodeReplaced | typeof ErrorCodeServerShutdown | typeof ErrorCodeInternal | typeof ErrorCodeBadRequest | typeof ErrorCodeUnknownType | typeof ErrorCodeMessageTooLarge | typeof ErrorCodeForbidden | typeof ErrorCodeFeatureDisabled | typeof ErrorCodeNotInRoom | typeof ErrorCodeRoomNotFound | typeof ErrorCodeRoomFull | typeof ErrorCodeKicked | typeof ErrorCodeRoomClosed | typeof ErrorCodeShareNotFound | typeof ErrorCodeShareLimit | typeof ErrorCodeCodecNotSupported | typeof ErrorCodeSDPInvalid | typeof ErrorCodeStaleNegotiation | typeof ErrorCodeAgentTargetNotFound;
/**
 * CloseCode is a WebSocket close code (01 §12.2). The preceding error (scope connection or session) decides the
 * client's action; the close code is the fallback.
 */
export const CloseCodeNormal = 1000; // client logout or page unload; the server skips grace
export const CloseCodeGoingAway = 1001; // the browser's own close on unload, Go clients, server stop
export const CloseCodeUnsupportedData = 1003; // binary frame
export const CloseCodeAbnormal = 1006; // no close frame (network); never sent
export const CloseCodeMessageTooBig = 1009; // over the socket read limit (coder/websocket)
export const CloseCodeInternalError = 1011; // internal error
export const CloseCodeServiceRestart = 1012; // service restart (server_shutdown)
export const CloseCodeProtocolViolation = 4400; // bad_message, hello_required, a second hello
export const CloseCodeUnauthenticated = 4401; // unauthenticated, session_revoked
export const CloseCodeForbidden = 4403; // account_disabled
export const CloseCodeTimeout = 4408; // hello_timeout, idle_timeout
export const CloseCodeReplaced = 4409; // replaced by a resume on another socket
export const CloseCodeVersionUnsupported = 4426; // protocol_unsupported, client_outdated
export const CloseCodeRateLimited = 4429; // rate_limited (connection), too_many_connections
export const CloseCodeSlowConnection = 4503; // slow_connection (send queue full)
export type CloseCode = typeof CloseCodeNormal | typeof CloseCodeGoingAway | typeof CloseCodeUnsupportedData | typeof CloseCodeAbnormal | typeof CloseCodeMessageTooBig | typeof CloseCodeInternalError | typeof CloseCodeServiceRestart | typeof CloseCodeProtocolViolation | typeof CloseCodeUnauthenticated | typeof CloseCodeForbidden | typeof CloseCodeTimeout | typeof CloseCodeReplaced | typeof CloseCodeVersionUnsupported | typeof CloseCodeRateLimited | typeof CloseCodeSlowConnection;
/**
 * FieldError is returned by Validate methods (and Decode); the hub maps it to bad_request with params
 * {field, reason}.
 */
export interface FieldError {
  Field: string; // JSON path, e.g. "subs[3].video"
  Reason: string; // required|invalid|too_long|too_many|duplicate
}
export const FieldRequired = "required";
export const FieldInvalid = "invalid";
export const FieldTooLong = "too_long";
export const FieldTooMany = "too_many";
export const FieldDuplicate = "duplicate";

//////////
// source: hello.go

/**
 * Hello is the first message of every connection (01 §8.2). hello, welcome, error and the envelope are frozen
 * across all protocol versions (additive changes only), so any client can read the server's answer.
 */
export interface Hello {
  protocol: number /* int */; // the client's newest protocol version
  minProtocol: number /* int */; // the client's oldest protocol version
  features: Feature[];
  client: ClientInfo;
  role: Role;
  resumeToken?: Secret; // from the last welcome of the connection to resume (§10.3)
  auth?: HelloAuth; // only when the upgrade carried no valid cookie
  caps: Caps;
}
/**
 * HelloAuth carries a bearer token (native apps, M2+). M1 servers always answer unauthenticated.
 */
export interface HelloAuth {
  scheme: AuthScheme;
  token: Secret;
}
/**
 * AuthScheme is the credential scheme in HelloAuth.
 */
export type AuthScheme = string;
export const AuthSchemeBearer: AuthScheme = "bearer"; // the only scheme in v1 (TS: plain string)
/**
 * ClientInfo describes the client build. OS and version are never shown to other users (01 §17).
 */
export interface ClientInfo {
  kind: ClientKind;
  version: string; // SemVer of the client build; web = SPA build = server release
  os: ClientOS;
  browser?: string; // chrome|edge|firefox|safari|other; diagnostics only
}
/**
 * ClientKind is the kind of client. The server accepts unknown kinds ([a-z]{1,16}) and treats them like web.
 */
export const ClientKindWeb = "web";
export const ClientKindDesktop = "desktop"; // later (M2/M3/M4)
export const ClientKindMobile = "mobile"; // pending native apps
export const ClientKindTool = "tool"; // isshoni-loadtest, tests
export type ClientKind = typeof ClientKindWeb | typeof ClientKindDesktop | typeof ClientKindMobile | typeof ClientKindTool;
/**
 * ClientOS is the client's operating system (diagnostics only).
 */
export const ClientOSWindows = "windows";
export const ClientOSMacOS = "macos";
export const ClientOSLinux = "linux";
export const ClientOSIOS = "ios";
export const ClientOSAndroid = "android";
export const ClientOSChromeOS = "chromeos";
export const ClientOSOther = "other";
export type ClientOS = typeof ClientOSWindows | typeof ClientOSMacOS | typeof ClientOSLinux | typeof ClientOSIOS | typeof ClientOSAndroid | typeof ClientOSChromeOS | typeof ClientOSOther;
/**
 * Role decides what a connection may do (01 §6.3).
 */
export const RoleFull = "full";
export const RoleViewer = "viewer";
export const RolePublisher = "publisher"; // later (M2)
export const RoleAgent = "agent"; // later (M4)
export type Role = typeof RoleFull | typeof RoleViewer | typeof RolePublisher | typeof RoleAgent;
/**
 * Feature is a named optional capability within a protocol version (01 §6.2). A feature is active only if it is in
 * welcome.features.
 */
export const FeatureAgentRelay = "agent.relay";
export const FeatureUserConnections = "user.connections"; // later (M2)
export const FeatureSharePause = "share.pause"; // later (M2)
export const FeatureLayerMid = "layer.mid"; // later (M5)
export const FeatureICERefresh = "ice.refresh"; // later (TURN)
export type Feature = typeof FeatureAgentRelay | typeof FeatureUserConnections | typeof FeatureSharePause | typeof FeatureLayerMid | typeof FeatureICERefresh;
/**
 * Caps are the client's media capabilities. Web: from RTCRtpReceiver/RTCRtpSender.getCapabilities, H.264 entries with
 * packetization-mode=1 only, mapped to CodecKey (web/src/protocol/codecs.ts).
 */
export interface Caps {
  decode: CodecKey[];
  encode?: CodecKey[];
  simulcast?: boolean; // can send simulcast
  displayCapture?: boolean; // can share (getDisplayMedia or native capture)
}
/**
 * Welcome is the reply to hello.
 */
export interface Welcome {
  protocol: number /* int */;
  serverVersion: string;
  minClientVersion: string; // "" = no minimum
  features: Feature[];
  limits: Limits;
  iceServers: ICEServer[]; // M1: always [] (no STUN/TURN needed: the server has a public address)
  connectionId: string;
  resumeToken: Secret;
  resumed: boolean;
  roomId?: string; // set when resumed into a room
  defaultRoomId: string; // "lounge" (03 §8; changing the default room is later)
  user: UserInfo;
  serverTime: string;
}
/**
 * UserInfo is the connection's own user.
 */
export interface UserInfo {
  id: string;
  name: string; // what the UI shows: the username in M1 (03 has no display names yet)
  admin?: boolean;
}
/**
 * Limits are the server's limits for this connection, sent in welcome.
 */
export interface Limits {
  maxMessageBytes: number /* int */; // 65536
  /**
   * MaxSDPBytes: max pc.answer (sub) message; pub offers are limited to 65536 bytes and 8 m-lines by the SFU.
   */
  maxSdpBytes: number /* int */; // 262144
  maxSharesPerUser: number /* int */; // 4
  maxRoomParticipants?: number /* int */; // admin soft limit (03 maxParticipantsPerRoom); 0 = none
  maxRoomShares?: number /* int */; // admin soft limit (03 maxSharesPerRoom); 0 = none
  maxVideoBitrate?: number /* int64 */; // admin cap per share in bit/s (03 maxShareBitrateKbps × 1000); 0 = preset default
  messagesPerSecond: number /* int */; // 20
  messageBurst: number /* int */; // 100
  pingIntervalMs: number /* int */; // 15000
  idleTimeoutMs: number /* int */; // 45000
  graceMs: number /* int */; // 30000
}
/**
 * ICEServer is one STUN/TURN server (RTCIceServer shape). M1 sends none.
 */
export interface ICEServer {
  urls: string[];
  username?: string;
  credential?: Secret;
}
/**
 * Ping is the client's application-level heartbeat (01 §3.4).
 */
export interface Ping {
  t: number /* int64 */; // sender's clock in ms, echoed back
}
/**
 * Pong answers ping.
 */
export interface Pong {
  t: number /* int64 */;
  serverTimeMs: number /* int64 */;
}

//////////
// source: notify.go

/**
 * Invalidate tells the SPA which REST resources (03) changed, so it can refetch them (01 §8.12).
 */
export interface Invalidate {
  topics: Topic[];
}
/**
 * Topic names a group of REST resources. The exact REST paths per topic are 03's; the SPA maps topics to its query
 * keys (05). Clients ignore unknown topics.
 */
export const TopicRooms = "rooms"; // room list                    → everyone
export const TopicMe = "me"; // own account (name, admin)    → that user
export const TopicDevices = "devices"; // the user's sessions/devices  → that user
export const TopicAdminUsers = "admin.users"; // admins only
export const TopicAdminInvites = "admin.invites"; // admins only
export const TopicAdminApprovals = "admin.approvals"; // admins only
export const TopicAdminSettings = "admin.settings"; // admins only
export type Topic = typeof TopicRooms | typeof TopicMe | typeof TopicDevices | typeof TopicAdminUsers | typeof TopicAdminInvites | typeof TopicAdminApprovals | typeof TopicAdminSettings;
/**
 * ServerShutdown is sent to every connection before the server stops; error{server_shutdown} and close 1012 follow.
 */
export interface ServerShutdown {
  reason: ShutdownReason;
  reconnectInMs: number /* int */; // per connection, uniform random in [500, 3000]
}
/**
 * ShutdownReason says whether the server expects to come back.
 */
export const ShutdownReasonRestart = "restart"; // M1 always sends this (SIGTERM can't tell restart from stop)
export const ShutdownReasonStop = "stop";
export type ShutdownReason = typeof ShutdownReasonRestart | typeof ShutdownReasonStop;

//////////
// source: pc.go

/**
 * TrackKind is the media kind of a track.
 */
export const TrackKindVideo = "video";
export const TrackKindAudio = "audio";
export type TrackKind = typeof TrackKindVideo | typeof TrackKindAudio;
/**
 * PCKind names one of a connection's two PeerConnections. Each has a fixed offerer (01 §9 rule 1).
 */
export const PCKindPub = "pub"; // publish PC: the client offers
export const PCKindSub = "sub"; // subscribe PC: the server offers
export type PCKind = typeof PCKindPub | typeof PCKindSub;
/**
 * PCOffer is an SDP offer: from the client for pub, from the server for sub (01 §8.8, rules in §9).
 */
export interface PCOffer {
  pc: PCKind;
  gen: number /* uint32 */; // PC generation, starts at 1; the side that creates PCs increments it
  neg: number /* uint32 */; // offer number within gen, starts at 1; the offerer increments it
  sdp: SDP; // an ICE restart shows only here (new ICE credentials); there is no flag
  tracks: TrackRef[]; // every m-section currently carrying a share
}
/**
 * PCAnswer answers a PCOffer: from the server for pub, from the client for sub.
 */
export interface PCAnswer {
  pc: PCKind;
  gen: number /* uint32 */;
  neg: number /* uint32 */; // echoes the offer
  sdp: SDP;
}
/**
 * TrackRef maps one m-section of an offer to a share. Both sides use it, not msid.
 */
export interface TrackRef {
  mid: string;
  shareId: string;
  kind: TrackKind;
}
/**
 * PCICE carries one trickled ICE candidate. Clients trickle; the server puts all its candidates in its SDP.
 */
export interface PCICE {
  pc: PCKind;
  gen: number /* uint32 */;
  candidate?: ICECandidate; // absent = end of candidates (optional; the server ignores it)
}
/**
 * ICECandidate has the JSON shape of RTCIceCandidateInit and pion's webrtc.ICECandidateInit.
 */
export interface ICECandidate {
  candidate: string; // <= 512 bytes
  sdpMid?: string;
  sdpMLineIndex?: number /* uint16 */;
  usernameFragment?: string;
}
/**
 * PCRestart asks the offerer of a PC to restart ICE or rebuild the PC (§10.4).
 * Client -> server: sub only (mode ice or rebuild). Server -> client: pub only, mode rebuild (reason failed).
 */
export interface PCRestart {
  pc: PCKind;
  gen: number /* uint32 */; // generation the requester has now; stale requests are ignored
  mode: RestartMode;
  reason: RestartReason;
}
/**
 * RestartMode is how a PC recovers.
 */
export const RestartModeICE = "ice";
export const RestartModeRebuild = "rebuild";
export type RestartMode = typeof RestartModeICE | typeof RestartModeRebuild;
/**
 * RestartReason says why a restart is requested.
 */
export const RestartReasonDisconnected = "disconnected";
export const RestartReasonFailed = "failed";
export type RestartReason = typeof RestartReasonDisconnected | typeof RestartReasonFailed;
/**
 * PCClose tells the server the client closed its pub PC on purpose (no shares left, or leaving).
 * M1 clients send it only for pub; the server ignores pc: sub.
 */
export interface PCClose {
  pc: PCKind;
  gen: number /* uint32 */;
}

//////////
// source: quality.go

/**
 * QualityHint tells a sharer to change how it encodes one share. Policy (when and what): 02.
 */
export interface QualityHint {
  shareId: string;
  reason: HintReason;
  codec?: CodecKey; // set: switch profile (the client re-offers the pub PC with it first)
  encodings?: Encoding[]; // set: the complete list; apply every entry with setParameters (active, maxBitrate, ...)
  maxBitrate?: number /* int64 */; // native publishers (M2+): total cap, applied with hysteresis
}
/**
 * HintReason says why a quality.hint was sent. Clients show unknown reasons without a specific text.
 */
export const HintReasonViewers = "viewers"; // e.g. nobody watches high: deactivate "f"
export const HintReasonCongestion = "congestion"; // server uplink estimate
export const HintReasonCodec = "codec"; // room codec safe set changed
export const HintReasonPreset = "preset";
export const HintReasonAdmin = "admin";
export type HintReason = typeof HintReasonViewers | typeof HintReasonCongestion | typeof HintReasonCodec | typeof HintReasonPreset | typeof HintReasonAdmin;
/**
 * CapsUpdate reports changed capabilities (web: polled every 5 s while a subscription has reason codec). It is the
 * client's only part in codec recovery; all rebuild retries are server-driven (02 §8.5).
 */
export interface CapsUpdate {
  caps: Caps;
}

//////////
// source: registry.go

/**
 * Direction is the direction of a message. It is a bit set so Lookup can ask for either.
 */
export type Direction = number /* uint8 */;
export const DirClientToServer: Direction = 1;
export const DirServerToClient: Direction = 2;
/**
 * MsgKind says whether a message is a request, a reply or a notification (01 §7).
 */
export type MsgKind = number /* uint8 */;
export const KindRequest: MsgKind = 1; // has an id and gets exactly one reply
export const KindReply: MsgKind = 2; // welcome, ok and error (an error without re is a notification)
export const KindNotification: MsgKind = 3; // no id, no reply
/**
 * Spec describes one message type (and direction); Registry is the single list used by the hub's dispatcher,
 * the tests (every Spec has a fixture) and the TS generator.
 */
export interface Spec {
  Type: MessageType;
  Dir: Direction;
  Kind: MsgKind;
  Payload: any; // zero value of the payload type, e.g. RoomJoin{}; nil for ok (the request's Result applies)
  Reply: MessageType; // requests: MessageTypeOK, or MessageTypeWelcome for hello
  Result: any; // requests: zero value of the reply payload (Empty{} if none)
  Roles: Role[]; // client->server: allowed roles; nil = all (for pc.* the PC kind decides: Role.AllowsPC)
  Feature: Feature; // "" = baseline
  Since: number /* int */; // protocol version that introduced it
  Milestone: string; // "M1", "M2", ... (docs)
}

//////////
// source: room.go

/**
 * RoomJoin asks to join a room (01 §8.4). A malformed roomId gets room_not_found, like 03's REST 404.
 */
export interface RoomJoin {
  roomId: string;
}
/**
 * RoomJoinResult is the ok payload of room.join. A room.state for the room follows immediately.
 */
export interface RoomJoinResult {
  room: RoomInfo;
}
/**
 * RoomInfo identifies a room.
 */
export interface RoomInfo {
  id: string;
  name: string;
}
/**
 * RoomState is a full snapshot of one room (01 §8.5), coalesced to at most one per 200 ms per room. Every connection
 * in the room gets byte-identical snapshots.
 */
export interface RoomState {
  roomId: string;
  rev: number /* uint64 */; // +1 per change in this server process; clients reset on every welcome
  participants: ParticipantInfo[]; // sorted by joinedAt, then userId
  shares: ShareInfo[]; // sorted by startedAt, then id
}
/**
 * ParticipantInfo merges all connections of one user in one room.
 */
export interface ParticipantInfo {
  userId: string;
  name: string;
  status: ParticipantStatus;
  joinedAt: string;
  connections: ConnectionInfo[];
}
/**
 * ParticipantStatus is present while at least one connection is ready. Clients treat unknown values as present.
 */
export const ParticipantStatusPresent = "present";
export const ParticipantStatusReconnecting = "reconnecting";
export type ParticipantStatus = typeof ParticipantStatusPresent | typeof ParticipantStatusReconnecting;
/**
 * ConnectionInfo is what everyone in the room sees about a connection. OS and version are deliberately absent
 * (privacy); admins get them from the live snapshot (01 §15.2), the user's own devices from user.connections (M2).
 * OwnConnection embeds it, so it must never get a MarshalJSON method (the embedding would hide OwnConnection's own
 * fields).
 */
export interface ConnectionInfo {
  id: string;
  kind: ClientKind;
  role: Role;
  status: ConnectionStatus;
}
/**
 * ConnectionStatus is online while the connection's socket is attached. Clients treat unknown values as online.
 */
export const ConnectionStatusOnline = "online";
export const ConnectionStatusReconnecting = "reconnecting";
export type ConnectionStatus = typeof ConnectionStatusOnline | typeof ConnectionStatusReconnecting;
/**
 * ShareInfo describes one share in room.state.
 */
export interface ShareInfo {
  id: string;
  userId: string;
  connectionId: string; // the publishing connection
  kind: ShareKind;
  label?: string; // absent: viewers render t('share.label.<kind>')
  preset: Preset;
  audio: boolean; // declared at start; after live: whether an audio track arrived
  status: ShareStatus;
  layers: VideoLayer[]; // layers whose tracks arrived (paused layers included), e.g. ["high","low"]; [] while starting
  codec?: CodecKey; // H.264 profile currently published
  startedAt: string;
  replaces?: string; // re-publish after a restart/rebuild (§10.6)
  watchers: Watcher[]; // excludes the owner (§4.1); "N watching" is len(watchers)
}
/**
 * Watcher is one participant receiving a share's video at any layer or its audio (01 §4.1), from the desired
 * subscriptions, merged over the participant's connections.
 */
export interface Watcher {
  userId: string;
  video: VideoLayer;
  audio: AudioState;
}
/**
 * RoomEvent announces a discrete change for toasts and aria-live (01 §8.6). Events are never part of a snapshot and
 * are not sent on join or resume; the UI renders from room.state.
 */
export interface RoomEvent {
  kind: RoomEventKind;
  roomId: string;
  userId: string;
  name: string; // so a toast works after the person left the snapshot
  shareId?: string;
  replaces?: string; // share.started of a re-publish: clients suppress the toast
  reason?: EndReason; // share.stopped, participant.left
  at: string;
}
/**
 * RoomEventKind is the kind of a room.event. Clients ignore unknown kinds.
 */
export const RoomEventKindParticipantJoined = "participant.joined";
export const RoomEventKindParticipantLeft = "participant.left";
export const RoomEventKindShareStarted = "share.started"; // on starting → live, once per share
export const RoomEventKindShareStopped = "share.stopped";
export type RoomEventKind = typeof RoomEventKindParticipantJoined | typeof RoomEventKindParticipantLeft | typeof RoomEventKindShareStarted | typeof RoomEventKindShareStopped;
/**
 * EndReason says why a share ended or a participant left. The strings are identical in 02's sfu package. Clients
 * show unknown reasons without a specific text.
 */
export const EndReasonStopped = "stopped"; // share.stop, pc.close, or tracks removed by the owner
export const EndReasonLeft = "left"; // room.leave / room.join elsewhere / deliberate close / closed by revocation (03)
export const EndReasonDisconnected = "disconnected"; // grace expired
export const EndReasonMediaTimeout = "media_timeout"; // starting or stalled for 30 s
export const EndReasonKicked = "kicked"; // reserved: admin kick is later
export const EndReasonRoomClosed = "room_closed"; // an admin deleted the room
export const EndReasonServerShutdown = "server_shutdown"; // shares only; never seen by clients of the new process
export type EndReason = typeof EndReasonStopped | typeof EndReasonLeft | typeof EndReasonDisconnected | typeof EndReasonMediaTimeout | typeof EndReasonKicked | typeof EndReasonRoomClosed | typeof EndReasonServerShutdown;

//////////
// source: scan.go


//////////
// source: secret.go

/**
 * Secret is a string that never appears in logs or fmt output; JSON encodes it verbatim (it is a plain string on
 * the wire). String, GoString, Format (every verb) and LogValue all return "[redacted]"; Reveal returns the value.
 * slog resolves a LogValuer only for an attribute's own value, and its JSON handler encodes any other struct with
 * encoding/json, which keeps a nested Secret or SDP verbatim. So every payload struct that holds a Secret, an SDP or
 * a candidate address (Hello, HelloAuth, Welcome, ICEServer, PCOffer, PCAnswer, PCICE) has its own LogValue that
 * logs a redacted summary. A slice of them ([]ICEServer) is still encoded field by field: log such values one by one.
 * (fmt and slog's text handler call Format on struct fields and redact them.)
 */
export type Secret = string;
/**
 * SDP is a session description. In logs and fmt output it shows only its length ("[sdp 5123 B]"); JSON encodes it
 * verbatim.
 */
export type SDP = string;

//////////
// source: share.go

/**
 * ShareStart starts a share (01 §8.7). The reply is its ShareParams; the client then offers the share's tracks on
 * the pub PC.
 */
export interface ShareStart {
  kind: ShareKind;
  label?: string; // user-typed only; <= 40 code points
  preset: Preset;
  audio: boolean; // an audio track will be sent
  ref: string; // client idempotency key, 1-32 chars, unique per connection
  replaces?: string; // previous shareId of the same local capture (§10.6)
}
/**
 * ShareParams tells the sharer how to encode. The server computes it from the preset, the room's codec safe set and
 * admin limits (policy and numbers: 02). Encodings is in wire order, high first (f, then q); that is not the order
 * a web client gives the browser. Web clients (05 §13.4) pass complete sendEncodings to addTransceiver in ascending
 * order (q, then f), each with rid, active, maxBitrate, maxFramerate and scaleResolutionDownBy =
 * max(1, sqrt(width*height/maxPixels)). Later changes go through RTCRtpSender.setParameters, matched by rid.
 */
export interface ShareParams {
  shareId: string;
  codec: CodecKey; // H.264 profile to put first in setCodecPreferences
  encodings: Encoding[]; // wire order, high first (f, q); not the sendEncodings order
  audioBitrate: number /* int */; // Opus target in bit/s (the pub answer's maxaveragebitrate)
}
/**
 * Encoding is one simulcast layer's encoder settings.
 */
export interface Encoding {
  rid: string; // RIDHigh or RIDLow
  layer: VideoLayer;
  active: boolean;
  maxBitrate: number /* int64 */;
  maxFramerate: number /* int */;
  maxPixels: number /* int */; // pixel budget, aspect-ratio neutral (ultrawide screens)
}
/**
 * ShareUpdate changes the label or preset of a share of the same user. The reply carries the new ShareParams.
 */
export interface ShareUpdate {
  shareId: string;
  label?: string; // "" clears the label
  preset?: Preset;
}
/**
 * ShareStop ends a share. It is idempotent: an unknown or already ended share replies ok.
 */
export interface ShareStop {
  shareId: string;
}
/**
 * ShareKind is what is being shared. Clients treat unknown values as screen.
 */
export const ShareKindScreen = "screen"; // getDisplayMedia displaySurface "monitor"
export const ShareKindWindow = "window"; // "window"
export const ShareKindTab = "tab"; // "browser"
export type ShareKind = typeof ShareKindScreen | typeof ShareKindWindow | typeof ShareKindTab;
/**
 * Preset is the sharer's quality preset (numbers: 02). Clients treat unknown values as auto.
 */
export const PresetAuto = "auto";
export const PresetGame = "game";
export const PresetMovie = "movie";
export const PresetText = "text";
export type Preset = typeof PresetAuto | typeof PresetGame | typeof PresetMovie | typeof PresetText;
/**
 * ShareStatus is a share's state (01 §4.4). Clients treat unknown values as live.
 */
export const ShareStatusStarting = "starting";
export const ShareStatusLive = "live";
export const ShareStatusStalled = "stalled";
export type ShareStatus = typeof ShareStatusStarting | typeof ShareStatusLive | typeof ShareStatusStalled;

//////////
// source: stats.go

/**
 * ClientStats is the client's stats report, sent every 10 s while it has a PC (01 §8.11). No IP addresses: the
 * candidate type only.
 */
export interface ClientStats {
  intervalMs: number /* int */;
  pcs: PCStats[];
  inbound?: InboundStats[];
  outbound?: OutboundStats[];
}
/**
 * PCStats describes one of the client's PCs.
 */
export interface PCStats {
  pc: PCKind;
  gen: number /* uint32 */;
  state: string; // RTCPeerConnectionState
  rttMs?: number /* int */;
  outgoingBitrate?: number /* int64 */; // availableOutgoingBitrate
  candidateType?: string; // local side of the selected pair: host|srflx|prflx|relay
  transport?: string; // udp|tcp
}
/**
 * InboundStats describes one received track.
 */
export interface InboundStats {
  shareId: string;
  kind: TrackKind;
  bitrate: number /* int64 */;
  packetsLost: number /* int64 */; // may be negative (RTCP cumulative loss with duplicates)
  jitterBufferMs?: number /* int */;
  fps?: number /* float64 */;
  width?: number /* int */;
  height?: number /* int */;
  freezeCount?: number /* int */;
  decoder?: string;
  hwDecoder?: boolean;
  codec?: CodecKey;
  /**
   * Cumulative counters since the track started (getStats values); the hub turns deltas into the
   * isshoni_client_* metrics of §18 for the M1 exit test (06 §12.3).
   */
  framesDecoded?: number /* int64 */;
  framesDropped?: number /* int64 */;
  freezeDurationMs?: number /* int64 */; // totalFreezesDuration
  concealedSamples?: number /* int64 */; // audio
  totalSamples?: number /* int64 */; // audio: totalSamplesReceived
}
/**
 * OutboundStats describes one sent track or simulcast layer.
 */
export interface OutboundStats {
  shareId: string;
  kind: TrackKind;
  rid?: string;
  bitrate: number /* int64 */;
  fps?: number /* float64 */;
  width?: number /* int */;
  height?: number /* int */;
  encoder?: string;
  hwEncoder?: boolean;
  qualityLimitation?: string; // none|cpu|bandwidth|other
}
/**
 * StatsWatch turns the server's stats stream for this connection on or off ("Stats for nerds").
 */
export interface StatsWatch {
  on: boolean;
}
/**
 * ServerStats is sent every 2 s while the connection watches stats; values come from MediaPeer.Stats() (02).
 */
export interface ServerStats {
  downlinkEstimate?: number /* int64 */; // bit/s for this connection's sub PC
  subs: ServerSubStats[];
  layers: ServerLayerStats[]; // this connection's own published layers
}
/**
 * ServerSubStats describes one forwarded track of this connection's subscriptions.
 */
export interface ServerSubStats {
  shareId: string;
  kind: TrackKind;
  layer?: VideoLayer; // video only
  bitrate: number /* int64 */;
  lossPct: number /* float64 */;
  dropped: number /* int64 */; // packets dropped by the DownTrack queue
}
/**
 * ServerLayerStats describes one received layer of this connection's own shares.
 */
export interface ServerLayerStats {
  shareId: string;
  kind: TrackKind;
  rid?: string;
  bitrate: number /* int64 */;
  lossPct: number /* float64 */;
}

//////////
// source: subscribe.go

/**
 * VideoLayer is a simulcast layer, or off. Clients treat unknown values in statuses and watchers as high.
 */
export const VideoLayerHigh = "high"; // rid "f": full (source, <=1080p60 by default)
export const VideoLayerLow = "low"; // rid "q": preview (360p15)
export const VideoLayerOff = "off";
export type VideoLayer = typeof VideoLayerHigh | typeof VideoLayerLow | typeof VideoLayerOff;
/**
 * AudioState says whether a subscription forwards a share's audio.
 */
export const AudioStateOn = "on";
export const AudioStateOff = "off";
export type AudioState = typeof AudioStateOn | typeof AudioStateOff;
export const RIDHigh = "f";
export const RIDLow = "q";
/**
 * RIDs used in simulcast for each layer. Fixed for all senders (browser and native).
 */
export type RID = typeof RIDHigh | typeof RIDLow;
/**
 * SubscribeUpdate is desired state per share, merged into the connection's existing wants (01 §8.9). All changes of
 * one user action go in one update, so the server applies them atomically (audio follows focus).
 */
export interface SubscribeUpdate {
  subs: SubscriptionWant[]; // 1..64 items, unique shareIds
}
/**
 * SubscriptionWant is the desired video layer and audio of one share. {off, off} pauses a subscription but keeps its
 * transceivers.
 */
export interface SubscriptionWant {
  shareId: string;
  video: VideoLayer;
  audio: AudioState;
}
/**
 * SubscribeResult is the ok payload of subscribe.update.
 */
export interface SubscribeResult {
  ignored: string[]; // shareIds that don't exist (any more) in the connection's room
}
/**
 * SubscribeStatus reports forwarding that differs from the request, or changes back.
 */
export interface SubscribeStatus {
  subs: SubscriptionStatus[]; // only the subscriptions whose status changed
}
/**
 * SubscriptionStatus is what the server forwards for one subscription now.
 */
export interface SubscriptionStatus {
  shareId: string;
  video: VideoLayer; // being forwarded now
  audio: AudioState;
  requestedVideo: VideoLayer;
  reason?: StatusReason; // absent: video == requestedVideo
}
/**
 * StatusReason says why forwarding differs from the request. 02's finer reasons are mapped to these four (§15.4).
 * Clients show unknown reasons without a specific text.
 */
export const StatusReasonBandwidth = "bandwidth"; // server downgraded (REMB/loss estimate, 02)
export const StatusReasonUnavailable = "unavailable"; // publisher doesn't send that layer (now)
export const StatusReasonCodec = "codec"; // this client can't decode the share's codec (§11.7)
export const StatusReasonWaiting = "waiting"; // sub PC not connected yet, or waiting for a keyframe
export type StatusReason = typeof StatusReasonBandwidth | typeof StatusReasonUnavailable | typeof StatusReasonCodec | typeof StatusReasonWaiting;

//////////
// source: validate.go

export const MaxMessageBytes = 64 << 10; // every message before welcome, and every non-SDP message after
export const MaxSDPBytes = 256 << 10; // pc.offer and pc.answer after welcome (welcome.limits.maxSdpBytes)
export const MaxStatsBytes = 16 << 10; // a client stats message
export const MaxIDLen = 32; // envelope id and re, share.start ref
export const MaxOpaqueIDLen = 64; // user, room, share and connection ids: [A-Za-z0-9_-]{1,64}
export const MaxLabelRunes = 40; // share label, in Unicode code points after trimming
export const MaxSubs = 64; // subscribe.update items
export const MaxPubTracks = 8; // tracks of a pub offer (m-sections carrying a share)
export const MaxConnSubscriptions = 256; // subscriptions per connection (02 §12, sfu.too_many_subscriptions)
export const MaxSubTracks = 2 * MaxConnSubscriptions; // tracks of a sub offer: video and audio of every subscription
export const MaxCandidateBytes = 512; // pc.ice candidate string
export const MaxFeatures = 32; // hello.features
export const MaxCodecs = 32; // caps.decode, caps.encode
export const MaxAgentKindLen = 32; // agent.send kind: [a-z.]{1,32}
export const MaxAgentPayloadBytes = 16 << 10; // agent.send payload
