// Code generated by TestSFUParserCopy from internal/server/sfu/h264.go; DO NOT EDIT.

// A verbatim copy of parseSPS, isKeyframeStart and what they use (sfucopy_test.go).

package fake

import (
	"errors"
	"fmt"
)

// H.264 NAL unit types (RFC 6184, H.264 Table 7-1) the SFU looks at.
const (
	nalTypeSPS   = 7
	nalTypeSTAPA = 24
	nalTypeMask  = 0x1f
)

// isKeyframeStart reports whether an H.264 RTP payload starts a keyframe a decoder can start from: its first NAL is an
// SPS, or it is a STAP-A that holds one (02 §9.1, kept from S4). Layer switches and resumes happen only on such a
// packet, because switching on a later one (a bare IDR, say) would leave the decoder without the new layer's SPS and
// PPS, whose resolution differs from the old layer's. It runs for every video packet: no allocation, and the STAP-A
// walk is bounds-checked (FuzzKeyframeStart).
func isKeyframeStart(payload []byte) bool {
	return spsNAL(payload) != nil
}

// spsNAL returns the SPS NAL unit (with its one-byte header) that an H.264 RTP payload carries as a single NAL unit or
// inside a STAP-A, or nil. The result aliases payload. A STAP-A is walked until its first SPS; an aggregation unit with
// size 0 or one that runs past the end stops the walk.
func spsNAL(payload []byte) []byte {
	if len(payload) == 0 {
		return nil
	}
	switch payload[0] & nalTypeMask {
	case nalTypeSPS:
		return payload
	case nalTypeSTAPA:
		for i := 1; i+2 < len(payload); {
			size := int(payload[i])<<8 | int(payload[i+1])
			i += 2
			if size == 0 || size > len(payload)-i {
				return nil
			}
			if payload[i]&nalTypeMask == nalTypeSPS {
				return payload[i : i+size]
			}
			i += size
		}
	}
	return nil
}

// spsInfo is what the SFU reads from an SPS, for LayerInfo and the dashboard (02 §9.1).
type spsInfo struct {
	profileIDC  uint8 // profile_idc: 66 Baseline, 77 Main, 100 High, …
	constraints uint8 // constraint_set0..5 flags plus 2 reserved bits, the middle byte of profile-level-id
	level       uint8 // level_idc (31 = 3.1)
	width       int   // display size in pixels, after frame cropping
	height      int
}

// profileLevelID returns the SPS's profile-level-id as SDP writes it, for example "640c1f". It is not a ProfileKey:
// encoders set constraint flags that the SDP doesn't (OpenH264's Constrained Baseline is "42c0…", the SDP's "42e0…"),
// so the stream profile of a packet comes from its PT (02 §9.1).
func (s spsInfo) profileLevelID() string {
	return fmt.Sprintf("%02x%02x%02x", s.profileIDC, s.constraints, s.level)
}

// Limits that keep parseSPS's work and results bounded on hostile input. The size limit is H.264 level 6.2's
// MaxFS (139264 macroblocks, 8K) and sqrt(8 × MaxFS) per dimension (Annex A.3.1).
const (
	spsMaxFrameMBs     = 139264
	spsMaxDimensionMBs = 1055
	spsMaxPOCCycle     = 255 // num_ref_frames_in_pic_order_cnt_cycle (7.4.2.1.1)
)

// errSPS is wrapped by every parseSPS error.
var errSPS = errors.New("sfu: bad H.264 SPS")

// parseSPS parses an SPS NAL unit (including its one-byte header) up to the frame cropping fields (H.264 7.3.2.1.1);
// the VUI is not needed. It is ported from the S2-VT spike's parser and runs in time linear in len(nal): every loop
// is bounded by a constant or consumes input bits (FuzzParseSPS).
func parseSPS(nal []byte) (spsInfo, error) {
	fail := func(why string) (spsInfo, error) { return spsInfo{}, fmt.Errorf("%w: %s", errSPS, why) }
	if len(nal) < 4 || nal[0]&nalTypeMask != nalTypeSPS {
		return fail("not an SPS NAL unit")
	}
	rbsp := unescapeRBSP(nal[1:])
	if len(rbsp) < 3 {
		return fail("too short")
	}
	s := spsInfo{profileIDC: rbsp[0], constraints: rbsp[1], level: rbsp[2]}
	r := bitReader{b: rbsp, pos: 24}
	if r.ue() > 31 { // seq_parameter_set_id
		return fail("seq_parameter_set_id out of range")
	}
	chromaFormat := uint32(1)
	if highProfileFamily(s.profileIDC) {
		chromaFormat = r.ue()
		if chromaFormat > 3 {
			return fail("chroma_format_idc out of range")
		}
		if chromaFormat == 3 {
			r.u(1) // separate_colour_plane_flag
		}
		lumaDepth8, chromaDepth8 := r.ue(), r.ue() // bit_depth_luma_minus8, bit_depth_chroma_minus8
		if lumaDepth8 > 6 || chromaDepth8 > 6 {
			return fail("bit depth out of range")
		}
		r.u(1)        // qpprime_y_zero_transform_bypass_flag
		if r.flag() { // seq_scaling_matrix_present_flag
			lists := 8
			if chromaFormat == 3 {
				lists = 12
			}
			for i := 0; i < lists && r.err == nil; i++ {
				if r.flag() { // seq_scaling_list_present_flag[i]
					size := 16
					if i >= 6 {
						size = 64
					}
					r.skipScalingList(size)
				}
			}
		}
	}
	if r.ue() > 12 { // log2_max_frame_num_minus4
		return fail("log2_max_frame_num out of range")
	}
	switch r.ue() { // pic_order_cnt_type
	case 0:
		if r.ue() > 12 { // log2_max_pic_order_cnt_lsb_minus4
			return fail("log2_max_pic_order_cnt_lsb out of range")
		}
	case 1:
		r.u(1) // delta_pic_order_always_zero_flag
		r.se() // offset_for_non_ref_pic
		r.se() // offset_for_top_to_bottom_field
		n := r.ue()
		if n > spsMaxPOCCycle {
			return fail("num_ref_frames_in_pic_order_cnt_cycle out of range")
		}
		for i := uint32(0); i < n && r.err == nil; i++ {
			r.se() // offset_for_ref_frame[i]
		}
	case 2:
	default:
		return fail("pic_order_cnt_type out of range")
	}
	r.ue() // max_num_ref_frames
	r.u(1) // gaps_in_frame_num_value_allowed_flag
	widthMBs := uint64(r.ue()) + 1
	heightMapUnits := uint64(r.ue()) + 1
	frameMBsOnly := r.flag()
	if !frameMBsOnly {
		r.u(1) // mb_adaptive_frame_field_flag
	}
	r.u(1) // direct_8x8_inference_flag
	var cropL, cropR, cropT, cropB uint32
	if r.flag() { // frame_cropping_flag
		cropL, cropR, cropT, cropB = r.ue(), r.ue(), r.ue(), r.ue()
	}
	if r.err != nil {
		return fail(r.err.Error())
	}

	fieldFactor := uint64(2)
	if frameMBsOnly {
		fieldFactor = 1
	}
	heightMBs := fieldFactor * heightMapUnits
	if widthMBs > spsMaxDimensionMBs || heightMBs > spsMaxDimensionMBs || widthMBs*heightMBs > spsMaxFrameMBs {
		return fail("frame size out of range")
	}
	// Crop units (7.4.2.1.1): chroma sample units for 4:2:0 and 4:2:2, luma samples for 4:4:4 and monochrome.
	cropX, cropY := uint64(1), fieldFactor
	switch chromaFormat {
	case 1:
		cropX, cropY = 2, 2*fieldFactor
	case 2:
		cropX, cropY = 2, fieldFactor
	}
	codedW, codedH := widthMBs*16, heightMBs*16
	// Each offset is below 2^32, so these products stay far below 2^64.
	cropW := cropX * (uint64(cropL) + uint64(cropR))
	cropH := cropY * (uint64(cropT) + uint64(cropB))
	if cropW >= codedW || cropH >= codedH {
		return fail("cropping larger than the frame")
	}
	// Both are at most spsMaxDimensionMBs × 16 here.
	s.width = int(codedW - cropW)  //nolint:gosec // ≤ 16880 (checked above)
	s.height = int(codedH - cropH) //nolint:gosec // ≤ 16880 (checked above)
	return s, nil
}

// highProfileFamily reports the profile_idc values whose SPS carries chroma format, bit depth and scaling matrices
// (H.264 7.3.2.1.1).
func highProfileFamily(profileIDC uint8) bool {
	switch profileIDC {
	case 100, 110, 122, 244, 44, 83, 86, 118, 128, 138, 139, 134, 135:
		return true
	}
	return false
}

// unescapeRBSP removes emulation-prevention bytes (00 00 03 → 00 00) from a NAL unit payload.
func unescapeRBSP(b []byte) []byte {
	out := make([]byte, 0, len(b))
	zeros := 0
	for _, c := range b {
		if zeros >= 2 && c == 3 {
			zeros = 0
			continue
		}
		out = append(out, c)
		if c == 0 {
			zeros++
		} else {
			zeros = 0
		}
	}
	return out
}

// errBitsShort is the bitReader's error when the input runs out.
var errBitsShort = errors.New("bitstream too short")

// errExpGolomb is the bitReader's error for an Exp-Golomb code longer than 32 bits.
var errExpGolomb = errors.New("bad Exp-Golomb code")

// bitReader reads an RBSP MSB first. After the first error every read returns 0 and err stays set, so a parser
// can read a run of fields and check err once.
type bitReader struct {
	b   []byte
	pos int // in bits
	err error
}

// u reads an n-bit unsigned value, n ≤ 32 (u(n) in H.264 7.2).
func (r *bitReader) u(n int) uint32 {
	var v uint32
	for range n {
		if r.err != nil {
			return 0
		}
		if r.pos >= len(r.b)*8 {
			r.err = errBitsShort
			return 0
		}
		bit := r.b[r.pos/8] >> (7 - uint(r.pos%8)) & 1
		v = v<<1 | uint32(bit)
		r.pos++
	}
	return v
}

func (r *bitReader) flag() bool { return r.u(1) == 1 }

// ue reads an unsigned Exp-Golomb code (ue(v), H.264 9.1). Codes longer than 32 bits are errors, so the result is at
// most 2^32-2.
func (r *bitReader) ue() uint32 {
	zeros := 0
	for {
		b := r.u(1)
		if r.err != nil {
			return 0
		}
		if b == 1 {
			break
		}
		zeros++
		if zeros > 31 {
			r.err = errExpGolomb
			return 0
		}
	}
	if zeros == 0 {
		return 0
	}
	rest := r.u(zeros)
	if r.err != nil {
		return 0
	}
	return (1<<uint(zeros) - 1) + rest
}

// se reads a signed Exp-Golomb code (se(v), H.264 9.1.1): between -(2^31-1) and 2^31-1.
func (r *bitReader) se() int64 {
	v := int64(r.ue())
	if v%2 == 1 {
		return (v + 1) / 2
	}
	return -v / 2
}

// skipScalingList reads one scaling_list() of the given size (H.264 7.3.2.1.1.1).
func (r *bitReader) skipScalingList(size int) {
	last, next := int64(8), int64(8)
	for j := 0; j < size && r.err == nil; j++ {
		if next != 0 {
			delta := r.se()
			next = ((last+delta)%256 + 256) % 256
		}
		if next != 0 {
			last = next
		}
	}
}
